(refactor) Introduce helper function to get well-formatted patient display name.
openmrs/openmrs-esm-core pull request #1003
Opened 2024-05-19 12:11 UTC by xprl-gjf

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.  
(No API changes made)

## Summary
FHIR patient responses may now include a well-formatted display name as per [FM2-631](https://openmrs.atlassian.net/browse/FM2-631).

Despite this, there are many locations in the O3 frontend where a patient name is displayed explicitly as `${givenName} ${familyName}`.

In going through the codebase to fix this, it becomes apparent that there is value in adopting a consistent approach to getting the patient display name. 

## Screenshots
N/A

## Related Issue
https://openmrs.atlassian.net/browse/O3-2115

## Other

2024-05-20 15:30 UTC, xprl-gjf commented
@ibacher I'd like to know if you think this is the correct place for this code, or should it be somewhere else such as `esm-patient-common-lib`. I don't know if `esm-patient-common-lib` is available for every module that needs this functionality, perhaps including cohort app, laboratory app, etc.

2024-05-20 16:42 UTC, ibacher requested changes
Thanks @xprl-gjf! A couple of notes:

1. This isn't a refactor at all. It's adding a new function to the library, so it's a `(feat)`.
2. We prefer to have tickets versus just PRs (the description here is fine for a ticket).
3. When adding a new file to one of the libraries, please include a `/** @category */` comment at the top.
4. Remember to actually run the commit scripts, particularly the documentation script.

2024-05-20 16:42 UTC, ibacher commented on packages/framework/esm-utils/src/patient-helpers.ts
> +export function displayName(fhirPatient): string {
So, `fhirPatient` here should be typed. The typings for this usually live (for a number of reasons) in the esm-api sub-library, so that's probably the most reasonable place to move these to.

2024-05-20 16:42 UTC, ibacher commented on packages/framework/esm-utils/src/patient-helpers.ts
> +  return `${fhirPatient.name?.[0].given?.join(' ')} ${fhirPatient?.name?.[0].family}`;
For a library, it's best to get this right, i.e., never return "undefined" or "undefined undefined":

```suggestion
   if (!fhirPatient.name?.[0]) {
     return '';
   }
   
   const name = `${fhirPatient.name[0].given?.join(' ') ?? ''}`;
   
   return fhirPatient.name[0].family ? (name.length > 0 ? ' ' : '') + `fhirPatient.name[0].family` : name;
```

2024-05-20 16:42 UTC, ibacher commented
PS Yes, it's perfectly acceptable to put something like this here.

2024-05-21 03:17 UTC, xprl-gjf commented on packages/framework/esm-utils/src/patient-helpers.ts
> +export function displayName(fhirPatient): string {
Done; type fhir.Patient was already available.

2024-05-21 03:20 UTC, xprl-gjf commented on packages/framework/esm-utils/src/patient-helpers.ts
> +  return `${fhirPatient.name?.[0].given?.join(' ')} ${fhirPatient?.name?.[0].family}`;
OK. I have actually rewritten this code substantially to introduce functionality to `selectPreferredName`...
I have ensured I never return "undefined"

2024-05-21 20:17 UTC, ibacher approved these changes

2024-05-21 20:27 UTC, merged

2024-05-24 19:52 UTC, gracepotma commented
Wow, thank you @xprl-gjf!