(feat) Add additional properties for OpenmrsDatePicker in Carbon
openmrs/openmrs-esm-core pull request #1007
Opened 2024-05-22 05:31 UTC by kajambiya

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
There's a requirement to adopt the OpenmrsDatepicker on the REACT form engine. As such, it was imperative that the OpenmrsDatepicker is extended to support all the features that the RFE Datepicker currently supports.

## Screenshots

## Related Issue

## Other

2024-05-23 20:12 UTC, denniskigen approved these changes
Thanks

2024-05-23 20:43 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/openmrs/openmrs-date-picker.component.tsx
> +  readonly?: string | boolean;
[Carbon only supports booleans here](https://github.com/carbon-design-system/carbon/blob/5078eb5204b21763244768af3b0b283551561d47/packages/react/src/components/DatePickerInput/DatePickerInput.tsx#L178). The RFE must convert these to booleans before passing the prop to the component. Otherwise, `"false"` will be treated as true.

```suggestion
  readonly?: boolean;
```

2024-05-23 20:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/openmrs/openmrs-date-picker.component.tsx
> +  labelText: string | any;
Technically, what's supported here is [this](https://github.com/carbon-design-system/carbon/blob/5078eb5204b21763244768af3b0b283551561d47/packages/react/src/components/DatePickerInput/DatePickerInput.tsx#L19). No explicit `any`s should be added to the framework unless its unavoidable.

```suggestion
  labelText: string | ReactElement;
```

2024-05-23 20:51 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/openmrs/openmrs-date-picker.component.tsx
> +        onChange={(e) => onChange(dayjs(e.target.value, DEFAULT_PLACEHOLDER.toUpperCase()).toDate())}
`onChange` in the `DatePickerInput` is not a React pseudo-event and cannot be correctly triggered using the React Testing Library. That's because the Carbon DatePicker is a wrapper around the `flatpickr` library. I'd prefer we didn't add a do-nothing handler here. The right thing to do would be to use a `ref` to get the `div` the `DatePicker` creates, get the actual `input` element underneith it and fire it's change event.

2024-05-23 20:52 UTC, ibacher requested changes
See my remarks for changes that should be made here. Thanks!

2024-05-31 19:58 UTC, kajambiya commented
> See my remarks for changes that should be made here. Thanks!

Thanks @ibacher 
I've updated the code accordingly

2024-06-05 17:02 UTC, merged