(feat) O3-3390 : Implement Help Menu for User Onboardings
openmrs/openmrs-esm-core pull request #1034
Opened 2024-06-08 17:44 UTC by Vijaykv5

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR implements the [help menu ](https://zeroheight.com/23a080e38/p/55ee46-help-menu/t/76fa67) along with it's submenu in a new module named `esm-help-menu-app`

## Screenshots

https://github.com/openmrs/openmrs-esm-core/assets/94985341/08970145-806e-4de1-a9c6-634fc241201f

## Related Issue

[O3-3390 ](https://openmrs.atlassian.net/browse/O3-3390)

## Other

The help menu is design as per these [Zeplin Designs](https://zpl.io/jZrNGl6)

2024-06-08 18:18 UTC, Vijaykv5 commented
@Piumal1999 @jayasanka-sack @ibacher @denniskigen seeking you review 
Thanks!

2024-06-13 18:46 UTC, ibacher requested changes
A couple of broader things:

* Ideally, this would be located where the devtools button is. Maybe we move the devtools.
* I'm not a massive fan of the modal side menu. I think a larger modal in the middle of the screen makes more sense.
* The release notes should be an accordion that expands to show the notes.

2024-06-13 18:46 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/helpMenu/subHelpMenu/tutorial.tsx
> +      {' '}
Please remove these spacers.

2024-06-13 18:46 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
This should be an extension slot and each of these buttons probably an extension.

2024-06-13 18:46 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
Display strings also need to be translatable.

2024-06-13 18:46 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.styles.scss
> +  margin: 3px;
Please use Carbon's spacing utility and rems for all of these things.

2024-06-13 18:46 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.styles.scss
> +.modalHeader {
Please use the standard Carbon designs here.

2024-06-18 07:36 UTC, jayasanka-sack commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
@Vijaykv5 The extension slot should come here, right? Not the `help.component.tsx`
```suggestion
        <ExtensionSlot className={styles.helpMenuExtension} name="help-menu-slot"/>
```

2024-06-18 08:02 UTC, Vijaykv5 commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
yeah that's right!
I thought the help menu **button** should also have to be an extension.

2024-06-19 10:13 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
@jayasanka-sack, just to clarify, we will be using extension slots in two scenarios, right?
1. To get the list of items in the help menu
2. To load the tutorials list

2024-06-19 10:13 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
By the way, if you do the suggested change now, we will have to create an extension for the `help-menu-slot` with `packages/apps/esm-help-menu-app/src/helpMenu/subHelpMenu/tutorial.tsx` component. Otherwise, there won’t be a way to open the tutorial modal.

2024-06-20 14:11 UTC, jayasanka-sack commented on packages/apps/esm-help-menu-app/src/helpMenu/help-popup.component.tsx
> +        </button>
> just to clarify, we will be using extension slots in two scenarios, right?

@Piumal1999 yes

2024-06-20 20:18 UTC, Vijaykv5 commented
The updated changes must looks like this 
<details><summary>Help Menu</summary>
<p>

https://github.com/openmrs/openmrs-esm-core/assets/94985341/3e7db09f-dbab-4f33-b5bb-21ffe784df9c


</p>
</details> 
cc : @jayasanka-sack @Piumal1999

2024-06-23 08:25 UTC, Piumal1999 reviewed
Good job @Vijaykv5. I requested few minor changes.

Btw, for the contact us, docs, and release notes buttons, we could use a single reusable component, as all three have the same structure, styles, and behavior. But we can do it later as this PR needs to be merged as soon as possible in order to continue the project.

2024-06-23 08:25 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/index.ts
> +export const help = getSyncLifecycle(Help, options);
This has to be replaced with the `root.component.tsx` as it's the root of the module


```
export const root = getAsyncLifecycle(() => import('./root.component'), options);
```

2024-06-23 08:25 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/index.ts
> +export const help = getSyncLifecycle(Help, options);
So in routes.json, the pages field will be like this:
```
"pages": [
    {
      "component": "root",
      "route": true
    }
  ],
```

2024-06-23 08:25 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/root.component.tsx
> +}
```suggestion
const Root: React.FC = () => {
  return (
    <HelpMenu />
  );
};

export default Root;
```

2024-06-23 08:25 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/help-menu/components/contact-us.component.tsx
> +    navigate({ to: 'https://openmrs.org/contact/' });
I think it would be better to open these in new tabs

2024-06-24 16:50 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/src/help-menu/help.component.tsx
> +      if (!event.target.closest(`.${styles.helpMenuButton}`) && !event.target.closest(`.${styles.popup}`)) {
It would be better if we could identify the event in some other way than using styles.

2024-06-24 16:51 UTC, Piumal1999 approved these changes
Looks good to me

2024-06-25 15:02 UTC, gracepotma commented
Could we change "Contact us" to "Community Forum" and link that to talk.openmrs.org ?

2024-06-26 12:47 UTC, jayasanka-sack commented
Latest screenshot: 

![image](https://github.com/openmrs/openmrs-esm-core/assets/33048395/969908ae-55d7-4199-99a4-3d938ae79844)

2024-06-26 13:42 UTC, jayasanka-sack commented
Good job, @Vijaykv5 !

2024-06-26 13:46 UTC, jayasanka-sack commented
> * Ideally, this would be located where the devtools button is. Maybe we move the devtools.
> * I'm not a massive fan of the modal side menu. I think a larger modal in the middle of the screen makes more sense.
> * The release notes should be an accordion that expands to show the notes.

@paulsonder @gracepotma do you have any input on this suggestion?

2024-07-01 16:27 UTC, jayasanka-sack commented
@Vijaykv5 could you please check why the CI build is failing?

2024-07-01 16:51 UTC, denniskigen reviewed
Good start, @vijaykv5. I've left some feedback.

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/components/contact-us.component.tsx
> +  );
```suggestion
  return (
    <Link
      className={styles.helpButton}
      href="https://talk.openmrs.org"
      rel="noopener noreferrer"
      renderIcon={ArrowUpRight}
      target="_blank"
    >
      {t('communityforum', 'Community forum')}
    </Link>
  );
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/components/contact-us.component.tsx
> +import { ArrowUpRight } from '@carbon/react/icons';
```suggestion
import { ArrowUpRight } from '@carbon/react/icons';
import { Link } from '@carbon/react';
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/components/docs.component.tsx
> +  );
```suggestion
return (
    <Link
      className={styles.helpButton}
      href="https://o3-docs.openmrs.org"
      rel="noopener noreferrer"
      renderIcon={ArrowUpRight}
      target="_blank"
    >
      {t('docs', 'Docs')}
    </Link>
  );
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/components/release-notes.component.tsx
> +  );
```suggestion
return (
    <Link
      className={styles.helpButton}
      href="https://o3-docs.openmrs.org/docs/changelog"
      rel="noopener noreferrer"
      renderIcon={ArrowUpRight}
      target="_blank"
    >
      {t('releaseNotes', 'Release notes')}
    </Link>
  );
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/components/styles.scss
> +}
```suggestion
@use '@carbon/layout';
@use '@carbon/type';
@import '~@openmrs/esm-styleguide/src/vars';

.helpButton {
  margin: layout.$spacing-04;
  padding: layout.$spacing-01;
  cursor: pointer;
  text-align: left;
  display: flex;
  align-items: center;
  justify-content: space-between;
  color: black !important;

  &:focus {
    outline: none;
  }
}
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.component.tsx
> +  }, [helpMenuOpen]);
```suggestion
 useEffect(() => {
    const handleClickOutside = (event) => {
      if (
        helpMenuButtonRef.current &&
        !helpMenuButtonRef.current.contains(event.target) &&
        popupRef.current &&
        !popupRef.current.contains(event.target)
      ) {
        setHelpMenuOpen(false);
      }
    };

    document.addEventListener('click', handleClickOutside);
    
    return () => {
      document.removeEventListener('click', handleClickOutside);
    };
  }, [helpMenuOpen]);
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.component.tsx
> +      )}
```suggestion
    <button
        aria-expanded={helpMenuOpen}
        aria-controls="help-menu-popup"
        onClick={toggleHelpMenu}
        ref={helpMenuButtonRef}
        className={classNames(styles.helpMenuButton)}
      >
        <Help size={24} />
      </button>
      {helpMenuOpen && (
        <div id="help-menu-popup" ref={popupRef} className={styles.helpMenuPopup}>
          <HelpMenuPopup />
        </div>
      )}
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.styles.css
This file should have a `.scss` extension.

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.styles.css
> +  border-radius: 2rem;
```suggestion
  z-index: 7900;
  background-color: white;
  height: 2.5rem !important;
  width: 2.5rem !important;
  bottom: 5rem;
  position: fixed;
  display: flex;
  justify-content: center;
  align-items: center;
  right: 0.5rem;
  border: none;
  box-shadow:
    0 1px 3px rgba(0, 0, 0, 0.1),
    0 1px 2px -1px rgba(0, 0, 0, 0.1);
  border-radius: 2rem;
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.styles.css
> +  border-radius: 2rem;
To get the button aligned with https://zpl.io/5E6PWgW.

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/jest.config.js
> +    '\\.(m?j|t)sx?$': ['@swc/jest'],
```suggestion
    '^.+\\.tsx?$': ['@swc/jest'],
```

2024-07-01 16:51 UTC, denniskigen commented on packages/apps/esm-help-menu-app/jest.config.js
> +    'lodash-es': 'lodash',
```suggestion
    'lodash-es': 'lodash',
    '^lodash-es/(.*)$': 'lodash/$1',
```

2024-07-01 16:52 UTC, denniskigen commented on packages/apps/esm-help-menu-app/src/help-menu/help.styles.css
> +  border-radius: 2rem;
Just realized the link I posted might not be the latest available design. If not, feel free to ignore the background color change suggestion above.

2024-07-01 17:20 UTC, Vijaykv5 commented on packages/apps/esm-help-menu-app/src/help-menu/help.styles.css
> +  border-radius: 2rem;
Yes that's the latest design @denniskigen 
Thank you :)

2024-07-01 18:32 UTC, Vijaykv5 commented
Latest changes looks like this

https://github.com/openmrs/openmrs-esm-core/assets/94985341/0ae8a234-e7af-40b7-a752-67ffbc2b1b8c

2024-07-02 07:25 UTC, Piumal1999 commented on packages/apps/esm-help-menu-app/package.json
> +}
```suggestion
}

```

2024-07-02 14:40 UTC, jayasanka-sack approved these changes
Thanks @Vijaykv5 !

Merging this PR because the dev tools icon is only visible to admins, who rarely use the help functionality. However, we should discuss a proper decision in the next UX call.

2024-07-02 14:46 UTC, merged