(feat) Allow data sharing between workspaces with same sidebar family name
openmrs/openmrs-esm-core pull request #1094
Opened 2024-07-25 10:23 UTC by vasharma05

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This PR focuses on the workspaces with an action menu (sidebar) and can navigate between workspaces within the workspace itself.

1. Workspace with no action menu in itself, instead having the action menu outside of the workspace.
![image](https://github.com/user-attachments/assets/a6d907b4-88ab-429a-8be5-2f45ce5dcabd)

2. Workspace with action menu inside the workspace itself, where other workspace can be accessed via the action menu buttons only.
![image](https://github.com/user-attachments/assets/69bd76ed-a7e9-44d7-854a-2c2cbd397632)
![image](https://github.com/user-attachments/assets/70fe949e-6e68-4fd4-9f62-8027282f826a)

In the 1st scenario, the workspaces (order workspace, notes workspace) are independent of each other.

In the 2nd scenario, the workspaces are interlinked with some common data (as per the example screenshots, `patientUuid` and `bedId` is common data between the workspaces, and the new workspaces in the action menu are meant to be opened in the same context as of original workspace)

Taking an example of ward, user can click on the patient assigned to a bed and then the patient chart workspace will open on the right side. The other action menu buttons in the same workspaces are (for example) Transfers, in-patient notes, etc. Now the Transfers and In patient Notes workspaces share common data with the patient chart workspace, such as `patientUuid` and `bedNumber` assigned to the patient. 

To open the patient chart workspace, we can call: `launchPatientWorkspace('ward-patient-workspace', {patientUuid: <patientUuid>, bedNumber: <bedNumber>}').

Let's say, now we want to open the **Transfers** workspace, the action menu button will open it as `launchPatientWorkspace('transfer-patient-workspace')`. But the issue is that this function also needs the `patientUuid` and `bedNumber`. 

One way for this to happen is to pass the `additionalProps`(second arg of the `launchPatientWorkspace`) from the [WorkspaceRenderer](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-styleguide/src/workspaces/container/workspace-container.component.tsx#L127) to the [ActionMenu](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-styleguide/src/workspaces/container/workspace-container.component.tsx#L235), which can then be passed into the [ExtensionSlot](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-styleguide/src/workspaces/container/action-menu.component.tsx#L40) of the action menu, which then can be accessed by rendered Action Menu Buttons inside the above mentioned ExtensionSlot and then the Action Menu Button can take the same data from it's props and pass into the `launchPatientWorkspace` when launching, say, Transfers or In Patient Workspace.

In the above mechanism, the passing of the props from Action Menu to its respective `launchPatientWorkspace` is to be done by developer, which might be missed in some cases and it's a lot of props passing. Hence to improve the developer experience, we have come up with a workspace family store.

### Solution
The workspaces which have action menu in themselves has a registration property [hasOwnSidebar](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-extensions/src/workspaces.ts#L40) and [sidebarFamily](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-extensions/src/workspaces.ts#L41). If the workspaces have the same sidebarFamilyName, they need to share some common data, as explained above.

For these workspaces, a new property `workspaceFamilyStore` is added to the [OpenWorkspace](https://github.com/openmrs/openmrs-esm-core/blob/e1c8bd36795a8286576547c319c565680737b0db/packages/framework/esm-styleguide/src/workspaces/workspaces.ts#L96), which will point to the store of the workspaces sharing the same `sidebarFamilyName`. The workspaces can access the store using the `useWorkspaceFamilyStore` hook, passing the `sidebarFamilyName` into the hook and can access the data directly, without taking care of passing props from one component to another.

In case a workspace doesn't have a sidebar, the `workspaceFamilyStore` will be undefined for such workspaces, and the `useWorkspaceFamilyStore` hook will return empty data and dummy functions for such workspaces, since they are standalone workspaces.

## Screenshots
None

## Related Issue

## Other

2024-07-25 13:27 UTC, brandones requested changes

2024-07-25 13:27 UTC, brandones commented on packages/framework/esm-framework/docs/API.md
> +### useWorkspaceFamilyStore
Hi @vasharma05 , I would suggest doing this a little differently. I think we should not expose anything new in the API. Rather, new workspaces being opened in a sidebar family should just receive the correct additional props like magic. The workspace system itself will use `useWorkspaceFamilyStore` (or something like it) to pass the correct props to new workspaces. So everything happens behind the scenes. Does that make sense?

2024-07-29 15:15 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/container/workspace-renderer.component.tsx
> +        ...workspaceFamilyState,
```suggestion
        ...workspaceFamilyState,
        ...workspace.additionalProps,
```

The `additionalProps` that come directly from `launchWorkspace` are more specific, so I'd have those override the family state.

2024-07-29 15:18 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  workspaceFamilyStore?: StoreApi<object> | undefined;
```suggestion
  workspaceFamilyStore?: StoreApi<object>;
```

Seems redundant with the `?`, right?

2024-07-29 15:34 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    }));
Are you sure that the store clearing on line 315 is working? In my experience that wouldn't work, because setState does a shallow merge with the existing state object, and merging `{ foo: 0 }` with `{}` yields `{ foo: 0 }`, not `{}`. This was at least true of our old state manager (what was it called?); I'm not sure about zustand.

The way I worked around that in the past was to put everything inside a top-level element. So I suggest having everything contained in a top-level property called `props`. Then when you clear it by doing `setState({ props: {} })` it will actually set the props element to `{}`, because it is a shallow merge.

2024-07-29 15:37 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    workspaceFamilyStore: getWorkspaceFamilyStore(workspace.sidebarFamily, additionalProps),
Why are we adding this element to `OpenWorkspace`? It looks like we aren't using it.

2024-07-29 15:37 UTC, brandones requested changes
A few questions and suggestions

2024-07-30 06:18 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    }));
Hi @brandones!
Yes, I was facing the store clean-up issue and realized that we have a second arg `replace` in the `setState`. This overrides the previous state and makes it an empty object.

I have also written a test for the same here:
![image](https://github.com/user-attachments/assets/58105622-ba32-40a2-97c6-85d3a49185d5)

2024-07-30 06:40 UTC, vasharma05 commented
Hi @brandones!
I have pushed the required changes.
Thanks!

2024-07-30 13:21 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    /**
I'd put this docstring with either the `useWorkspaceFamilyStore` function or `getWorkspaceFamilyStore`?

2024-07-30 13:22 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    /**
Though I might add a comment here to the effect of

```
// initialize workspace family store
```

if that is indeed what is happening

2024-07-30 13:24 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +    it('should update the store state with new additionalProps if workspaces with same sidebarFamily name calls the function', () => {
```suggestion
    });

    it('should update the store state with new additionalProps if workspaces with same sidebarFamily name calls the function', () => {
```

2024-07-30 13:35 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +  describe('Testing workspace family store', () => {
Hmm, it's maybe a shame we don't have tests for WorkspaceRenderer. These tests feel like they're really heavy on implementation details—pretty fragile and we aren't even able to test the main idea of the change, which is "when I open a workspace with sidebar family 'foo' and args XYZ, and then I open another workspace with the same sidebar family, it should also receive args XYZ."

But that's just an aside; don't worry about it for this PR. Thanks for these tests.

2024-07-30 13:35 UTC, brandones approved these changes
A couple minor suggestions but LGTM

2024-07-30 13:38 UTC, brandones commented
Oh and please do file a ticket as @ibacher requested, and link it with the existing tickets that this supports.

2024-07-30 16:51 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    /**
Yes @brandones , that is what I am doing!

2024-07-30 16:52 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +  describe('Testing workspace family store', () => {
Yes, we have the test that store has args from both workspace, but aren't checking if the real workspaces are getting it or not. We should add that.

2024-07-30 17:47 UTC, brandones approved these changes
Great work, thanks @vasharma05 !

2024-07-30 17:47 UTC, merged