(feat) O3-3684 Improve duration representation of `age` function
openmrs/openmrs-esm-core pull request #1100
Opened 2024-07-30 20:07 UTC by chibongho

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This commit improves on the existing `age()` function to display an age (or time duration) that follows [this](https://webarchive.nationalarchives.gov.uk/ukgwa/20160921162509mp_/http://systems.digital.nhs.uk/data/cui/uig/patben.pdf) guideline for NHS.

## Screenshots

## Related Issue

## Other

2024-07-30 20:13 UTC, chibongho commented on packages/framework/esm-utils/src/age-helpers.ts
> -export function daysIntoYear(date: Date) {
I did a search on github and these exported functions don't seem used anywhere else.

2024-07-30 20:13 UTC, chibongho commented on packages/framework/esm-utils/src/age-helpers.ts
> +export function age(fromDate: dayjs.ConfigType, toDate: dayjs.ConfigType = dayjs()): string {
I changed the function to take in the `toDate` as well since I needed it for testing.

2024-07-30 20:22 UTC, ibacher requested changes
Code seems fine. I think we need better parameter names, though, before mergin this in.

2024-07-30 20:22 UTC, ibacher commented on packages/framework/esm-utils/src/age-helpers.ts
> + * @param toDate Optional. The right bound of the duration. Defaults to the current date
I don't find `fromDate` or `toDate` very intuitive here. I _think_ the variables are something like `birthDate` and `ageAtDate` or something like that.

2024-07-30 20:22 UTC, ibacher commented on packages/framework/esm-utils/src/age-helpers.ts
> +      return isLtr ? week + ' ' + day : day + ' ' + week;
It might be worth using the [formatjs `Intl.DurationFormat` polyfill](https://formatjs.io/docs/polyfills/intl-durationformat) for this instead of rolling our own...

Ditto for other places we're doing similar things.

2024-07-30 20:22 UTC, ibacher commented on packages/framework/esm-utils/src/age-helpers.ts
> -}
I don't quite get why we're removing these? Since they're exports, isn't there the chance  that we're relyiing on them elsewhere?

2024-07-31 14:49 UTC, chibongho commented on packages/framework/esm-utils/src/age-helpers.ts
> +      return isLtr ? week + ' ' + day : day + ' ' + week;
> It might be worth using the [formatjs `Intl.DurationFormat` polyfill](https://formatjs.io/docs/polyfills/intl-durationformat) for this instead of rolling our own...
> 
> Ditto for other places we're doing similar things.

Thanks. Much simpler with it.

2024-07-31 14:50 UTC, chibongho commented on packages/framework/esm-utils/src/age-helpers.ts
> + * @param toDate Optional. The right bound of the duration. Defaults to the current date
Changed to `birthDate` and `currentDate` (optional) instead.

2024-07-31 15:01 UTC, chibongho commented on packages/framework/esm-utils/src/age-helpers.ts
> -}
They looked really specific to the prior `age()` implementation, and was likely marked as export by mistake. I did a search on frontend code in `site:openmrs` on github and we don't seem to be using these elsewhere.

2024-07-31 15:08 UTC, ibacher approved these changes

2024-07-31 15:08 UTC, merged

2024-07-31 15:08 UTC, ibacher commented
Thanks @chibongho! This is great!

2024-07-31 15:55 UTC, ibacher commented on packages/framework/esm-utils/src/age-helpers.ts
> -}
Excellent! All I wanted to know was that we at least checked!