(fix) O3-3691: The workspace family store is resetting itself when we are launching new workspace of the same sidebar family
openmrs/openmrs-esm-core pull request #1103
Opened 2024-07-31 12:24 UTC by vasharma05

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
The issue comes from [this line](https://github.com/openmrs/openmrs-esm-core/blob/98118452809d1d8217059e24d4dc37096231d500/packages/framework/esm-styleguide/src/workspaces/workspaces.ts#L305) which does check that the workspaces remaining do have the same sidebar family name and doesn’t check the fact that the new workspace to be opened is of the same family, hence it shouldn’t clear the workspace.

Addition: Added tests for workspace renderer to test if the valid props are being passed into the workspace or not.

## Screenshots
None

## Related Issue
https://issues.openmrs.org/browse/O3-3691

## Other
Fun fact:
This issue would've been caught earlier if I hadn't added [this line](https://github.com/openmrs/openmrs-esm-core/blob/98118452809d1d8217059e24d4dc37096231d500/packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts#L512) in my previous PR #1094

2024-07-31 13:19 UTC, ibacher requested changes
Thanks @vasharma05! A couple of minor things. Overall question though: doesn't this remove the check for existing open workspaces while fixing a bug when opening a new workspace?

2024-07-31 13:19 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/container/workspace-renderer.test.tsx
> +        // @ts-ignore
Why are we using @ts-ignore here? (`// @ts-ignore` should generally have a comment explaining its use).

2024-07-31 13:19 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +   * @default true
```suggestion
  /**
   * Controls whether the workspace family store will be cleared when this workspace is closed. Defaults to true except when opening a new workspace of the same family.
   *
   * @default true
```

2024-07-31 13:19 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      // This condition is added here to check if the new workspace is of the same sidebar family as the current workspace.
```suggestion
```

2024-07-31 13:28 UTC, brandones commented
I would rather the family workspace store stayed out of the API entirely. There's no reason that workspace client code should know about family workspace stores, and if you expose that in the API, you have to explain the whole thing. We can avoid that by creating a new function, called something like `closeWorkspaceInternal`, which takes the `clearFamilyStore` option, and is called by both `closeWorkspace` and `promptBeforeLunchingWorkspace`. `closeWorkspace` would basically become a thin wrapper around `closeWorkspaceInternal`.

2024-08-01 13:12 UTC, vasharma05 commented
Hi @brandones @ibacher, requesting your review here.
Thanks!

2024-08-01 13:39 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  closeWorkspaceInternal(name, { ...options, clearWorkspaceFamilyStore: true });
```suggestion
  return closeWorkspaceInternal(name, { ...options, clearWorkspaceFamilyStore: true });
```

2024-08-01 13:41 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +    it('should not clear workspace family store if the workspace is closed and `clearWorkspaceFamilyStore` option is passed false', async () => {
I would rather we just test that the props are maintained if a workspace of the same family is launched. That's what we care about; the `clearWorkspaceFamilyStore` stuff is implementation details. And then we don't even have to export the internal function.

2024-08-01 13:44 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +
```suggestion
      // test that default options are interpolated when providing options to `closeWorkspace`
```

2024-08-01 13:56 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +    it('should not clear workspace family store if the workspace is closed and `clearWorkspaceFamilyStore` option is passed false', async () => {
True @brandones!
I verified that the scenario is being handled by the other test for validating that the workspace is not cleared when opening new workspace of same type.
Thanks!

2024-08-01 14:19 UTC, ibacher approved these changes

2024-08-01 17:29 UTC, merged