(feat) O3-3773 Support Summary Tiles component in esm-styleguide commons-lib
openmrs/openmrs-esm-core pull request #1113
Opened 2024-08-14 11:29 UTC by kajambiya

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This PR introduces the summary tile/card summary component to esm-styleguide.

## Screenshots
<img width="1614" alt="Screenshot 2024-08-14 at 14 26 52" src="https://github.com/user-attachments/assets/9aac947e-2b24-4bc8-9536-37dee4891138">

## Related Issue

## Other

2024-08-16 12:45 UTC, ibacher requested changes
* Please look through the checklist on the PR. There are items there that absolutely need to be done.
* Were you able to generate that screen shot using _this version_ of the component?
* I don't really understand the need for this component per se. Where is this intended to be used? How many times do we need it?

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/tile.scss
> +@import '../root.scss';
Don't do this. Follow the guidelines Dennis suggested yesterday on the call (or look through the developer docs)

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/summary-card-component.tsx
> +        groupedColumns.map((group) => (
Any time you're using a `map` you should supply a `key` to the component, either derived from the data or at least using the index of the item.

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/tile.scss
> +.cardTitle > h4:after {
The `h4` element has a class, so it seems like this could be better written using `.title:after`

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/tile.scss
> +  width: 2rem;
Please use the Carbon tokens for defining spacing wherever possible. This helps ensure that the UI remains consistent with Carbon guidelines.

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/tile.scss
> +  padding: 1px 0 16px 16px;
Nothing over 1px should be specified in px.

2024-08-16 12:45 UTC, ibacher commented on packages/framework/esm-styleguide/src/tile/tile.scss
> +.widgetContainer {
A number of these rules seem to not be used by this component, so they probably don't belong here.

2024-08-20 14:14 UTC, gracepotma commented
@ibacher to answer your question: 
> I don't really understand the need for this component per se. Where is this intended to be used? How many times do we need it?

It's a useful feature to have a clinical area-specific summary within different clinical views. This was actually a make-or-break requirement for Ampath at the very beginning of O3 :) The user story is, "As a healthcare staff member focused on X condition (eg HIV clinic, MCH clinic, etc), I need to immediately see some very specific information summarized for me, so I can rapidly get the key information relevant to my specialty." Examples here from OHRI:

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/15755071-9133-407b-8a1a-3c4bf5162d06">

<img width="1910" alt="image" src="https://github.com/user-attachments/assets/6c054ba6-fa59-4a89-ac47-4e5fd639eecb">

2024-08-20 16:28 UTC, ibacher commented
It seems then like this belongs more readily in the patient chart then, rather than the styleguide.

2024-08-21 10:40 UTC, ebambo commented
> > It seems then like this belongs more readily in the patient chart then, rather than the styleguide, more exactly, in the patient-common-lib.
> 
> My thoughts too. If there's no objection to this, I'm going to proceed and and transfer this code to patient-chart. I guess the same applies to [encounter-list](https://openmrs.atlassian.net/browse/O3-3772) as well. CC: @ebambo

No objections from my side, as long as this still works fine with the work @hadijahkyampeire is doing with the config schema.

2024-10-21 18:46 UTC, brandones commented
Ok closing this as it seems we've decided to do it in patient-chart.

2024-10-21 18:46 UTC, closed without merging