(feat) O3-3774: Add implementation for the Nav Group
openmrs/openmrs-esm-core pull request #1116
Opened 2024-08-16 13:09 UTC by hadijahkyampeire

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
- Moved the implementation of Nav Groups to the style guide.

## Screenshots
I couldn't link the framework to the patient chart so I tested with the primary navigation app instead and below is a demo.

https://github.com/user-attachments/assets/76f9e647-7963-409e-b261-a205ee0663aa

## Related Issue
- https://openmrs.atlassian.net/browse/O3-3774

## Other

2024-08-16 13:32 UTC, ibacher requested changes
I think this PR both extracts too much and too little. The only things we should need to move (AFAICT) are the generic-nav-group and maybe the generic-dashboard. I don't really see the value of or how anyone would even make use of the DashboardGroup stuff generically (it works in the chart, let's keep it there and simplify what this PR needs to do).

2024-08-16 13:32 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/CreateDashboardGroup.tsx
These components shouldn't be in `left-nav`. The `left-nav` component is it's own thing.

2024-08-16 13:32 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/nav-group.ts
> +export * from './generic-nav-group.component';
Why are we exporting stuff from here?

2024-08-16 13:32 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/nav-group.ts
> +export function registerNavGroup(slotName: string) {
Why do we need this store at all?

2024-08-16 13:32 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/generic-nav-group.component.tsx
> +export const genericNavGroupConfigSchema = {
This needs to be registered somewhere to have any kind of effect.

2024-08-16 13:33 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/generic-nav-group.component.tsx
> +export const genericNavGroupConfigSchema = {
To use this as an extension, it also needs to actually be registered with the extension system in some way.

2024-08-16 15:26 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/left-nav/generic-nav-group.component.tsx
> +export const genericNavGroupConfigSchema = {
Yes, I have registered it in the index of the style guide, thanks @ibacher

2024-08-16 15:27 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/left-nav/nav-group.ts
> +export * from './generic-nav-group.component';
I wanted to export all from one file, but I have fixed that.

2024-08-19 15:58 UTC, ibacher commented on packages/framework/esm-styleguide/src/left-nav/index.tsx
> -import type { SideNavProps } from '@carbon/react';
?

2024-08-19 15:58 UTC, ibacher commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +  title: {
Instead of `title` we should probably specify this as a translation key...

2024-08-19 15:58 UTC, ibacher commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +interface NavGroupProps {
```suggestion
export interface NavGroupProps {
```

2024-08-19 15:58 UTC, ibacher commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +export interface NavGroupConfig {
```suggestion 
interface NavGroupConfig {
```

2024-08-19 16:01 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/left-nav/index.tsx
> -import type { SideNavProps } from '@carbon/react';
This was some unused import I came across and just cleaned it up

2024-08-19 16:03 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +  title: {
@ibacher I don't understand the above review 🤔

2024-08-20 14:38 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +  title: {
I have tried to check for some examples but I can't get any, but I have done it in this way, I don't know if this is what you meant.
```js
 title: {
    _type: Type.Object,
    _description: 'The title of the nav group.',
    _default: {
      key: 'myGroupKey',
      value: 'My Group',
    },
  },
```

2024-08-20 16:20 UTC, ibacher commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +  title: {
So what I said was that the `title` should specify a translation key passed through the `t()` function. What I mean is we leave this configuration as-is except change the default value to something like `myGroup` and then in the component, we have:

```jsx
const { t } = useTranslations();
//...
// t('myGroup', 'My Group')
<AccordianItem title={t(title)} />
```

An object isn't terribly useful here because the goal is to not hard-code the string in the configuration, but to allow it to be translated.

2024-08-20 16:24 UTC, ibacher commented
So two other things need to happen for this PR to work:

1. We need to actually register this extension with the extension system (try renaming the extension to global-nav-group and defining one in configuration).
2. I still think we need to move the generic dashboard stuff into the styleguide.

2024-08-21 06:38 UTC, hadijahkyampeire commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +  title: {
ok, thanks

2024-08-21 11:00 UTC, hadijahkyampeire commented
@ibacher Most of what is in the generic-nav component is what is in the nav-group component unless if i am missing something

2024-08-21 11:03 UTC, hadijahkyampeire commented
By registering, do you mean creating a store and registering it in the store as they did in the common-lib? like this;
```js
const navGroupStore = createGlobalStore('global-nav-groups', { navGroups: [] });

export function registerNavGroup(slotName: string) {
  const store = navGroupStore.getState();
  navGroupStore.setState({ navGroups: [slotName, ...store.navGroups] });
}
```

2024-08-21 16:21 UTC, ibacher commented
> By registering, do you mean creating a store and registering it in the store as they did in the common-lib?

No. I mean actually registering the extension with the extension system, via the `registerExtension()` call at some point. For most apps, this is handled by having an appropriate entry in `routes.json`, so patient-chart does this with it's `nav-group` extension [here](https://github.com/openmrs/openmrs-esm-patient-chart/blob/627fc0e3fba80f58157a79c3a098a1a96b933469/packages/esm-patient-chart-app/src/routes.json#L138); without registering this extension with the extension system, there's no way to actually _use_ it (your video above uses the `nav-group` defined in patient chart).

This is why I commented suggesting to rename the extension `global-nav-group` for testing.

2024-08-29 11:17 UTC, hadijahkyampeire commented
@ibacher anything we haven't covered in the PR, just want to know if there is more work or just the final review.

2024-08-29 15:06 UTC, ibacher commented on packages/apps/esm-primary-navigation-app/src/index.ts
> +export const globalNavGroup = getSyncLifecycle(GlobalNavGroup, {
Use `getAsyncLifecycle()` here please.

```suggestion
export const globalNavGroup = getSyncLifecycle(GlobalNavGroup, {
```

2024-08-29 15:06 UTC, ibacher commented on packages/apps/esm-primary-navigation-app/src/routes.json
> +      "name": "global-nav-group",
It's fine to call this `nav-group`. I was just using `global-nav-group` as an example to show you that there was no extension registration.

2024-08-29 15:06 UTC, ibacher commented on packages/framework/esm-styleguide/src/index.ts
> +defineExtensionConfigSchema('global-nav-group-slot', globalNavGroupConfigSchema);
```suggestion
defineExtensionConfigSchema('nav-group', globalNavGroupConfigSchema);
```

2024-08-29 15:06 UTC, ibacher commented on packages/framework/esm-styleguide/src/index.ts
> +defineExtensionConfigSchema('global-nav-group-slot', globalNavGroupConfigSchema);
Slots are only used for _locating_ extensions. They are a space on a page. They have no _functional_ meaning in this context. Note, this needs to match the _name the extension is registered as_.

2024-08-29 15:06 UTC, ibacher commented on packages/framework/esm-styleguide/src/nav-group/index.tsx
> +    _default: 'global-nav-group-slot',
```suggestion
    _default: 'nav-group-slot',
```

2024-09-24 17:34 UTC, hadijahkyampeire commented
@ibacher do we still want to move this into core or we close it

2024-09-28 17:33 UTC, ibacher approved these changes

2024-09-29 10:25 UTC, merged