(fix) - O3-3189 - fix server-side pagination hook to handle error con…
openmrs/openmrs-esm-core pull request #1123
Opened 2024-08-26 19:54 UTC by chibongho

…ditions; add hook to fetch all data from server-side paginated endpoints

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

There were a few problems with this [PR](https://github.com/openmrs/openmrs-esm-core/pull/1114), which introduced new react hooks to handle server-side pagination. This new PR addresses them:
- The hooks provided could be used to fetch all results from the server (by requesting all pages), but it required some boilerplate code and was somewhat error prone (especially when handling request errors). This PR adds new hooks `useOpenmrsFetchAll` and `useFhirFetchAll` to address that.
- the `loadMore()` function returned by `useOpenmrsInfinite()` can result in infinite request loop as it did not handle request errors correctly.
- The hooks only provided support for OpenMRS REST endpoints. This PR also adds corresponding hooks to Fhir REST endpoints.

## Screenshots

## Related Issue

## Other

2024-08-27 14:30 UTC, mogoodrich requested changes
@chibongho  thanks for all your work on this...  I defer to @ibacher  @denniskigen  and @brandones  on the details, due to my lack of expertise in this area.

But, overall, this seems very well organized.  I did add a couple of comments.  One thing I didn't quite undersetand was the difference between "fetchAll" and "infinite".

Thanks again!

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-framework/docs/API.md
> +with the key "webservices.rest.maxResultsDefault". See: https://openmrs.atlassian.net/wiki/spaces/docs/pages/25469882/REST+Module
I'm not sure if the FHIR module uses this max result default as well, do you know @ibacher ?

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-framework/docs/API.md
> +This hook handles fetching results from all pages of a paginated FHIR REST endpoint.
Should/can we add more detail here?

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-framework/docs/API.md
> +▸ **useFhirInfinite**<`T`\>(`url`, `options?`): `UseServerInfiniteReturnObject`<`T`, `fhir.Bundle`\>
Should we/can we add more detail here?

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-framework/docs/API.md
> +This hook handles fetching results from all pages of a paginated OpenMRS REST endpoint.
Can we better explain how his differs from useOpenMRSInfinite?

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-framework/docs/interfaces/UseServerFetchAllOptions.md
> +If true, the data of any page as soon as they are fetched.
typo? missing verb?

2024-08-27 14:30 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useFhirPagination.ts
> + * with the key "webservices.rest.maxResultsDefault". See: https://openmrs.atlassian.net/wiki/spaces/docs/pages/25469882/REST+Module
See my comment above

2024-08-27 14:41 UTC, chibongho commented
The documentations are definitely on the messier side as is. I'll clean those up.

2024-08-27 14:51 UTC, chibongho commented on packages/framework/esm-framework/docs/API.md
> +with the key "webservices.rest.maxResultsDefault". See: https://openmrs.atlassian.net/wiki/spaces/docs/pages/25469882/REST+Module
I don't know what the config param is, but I think it's difficult. I'll just remove that line.

2024-09-03 13:13 UTC, chibongho commented
@ibacher @brandones @denniskigen @vasharma05 This should be ready for review now. Thanks.

2024-09-04 14:31 UTC, mogoodrich reviewed
Sorry, maybe it's me and I'm just not getting it, but I still don't understand the different between "Infinite" and "Pagination" in the two use methods...?

2024-09-04 14:31 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useFhirInfinite.ts
> + * This function is the FHIR counterpart of `useOpenmrsInfinite`.
This is the exact same description as for useFhirPagination?

2024-09-04 14:31 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useFhirPagination.ts
> + * This function is the FHIR counterpart of `useOpenmrsPagination`.
This is the exact same description as for useFhirInfinite?

2024-09-04 14:31 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useOpenmrsPagination.ts
> + * lazy-loads the data on each page as needed.
So is the different between useOpenmrsPagination and useOpenmrsInfinite just about the format of the callback functions it provides?

2024-09-04 14:31 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useOpenmrsInfinite.ts
> + * provide infinite loading / scrolling of results.
See my comment about useOpenmrsPagination...

2024-09-04 14:48 UTC, chibongho commented
> Sorry, maybe it's me and I'm just not getting it, but I still don't understand the different between "Infinite" and "Pagination" in the two use methods...?

(I find the useSWR documentation confusing on this as well, although we can certainly document our version of it better) If I understand correctly , `useInfinite` allows you do set `size` (the param for the # of pages to load) and it loads pages `0..size`. What it doesn't let you do is skipping to any arbitrary page without loading all pages preceding it, so if you only want to load the page 17, there is no way to do so without loading pages 0 to 16. 

`usePagination`, OTOH, allows skipping to any arbitrary page.

I'll add that do the comments.

2024-09-04 14:52 UTC, chibongho commented on packages/framework/esm-react-utils/src/useFhirInfinite.ts
> + * This function is the FHIR counterpart of `useOpenmrsInfinite`.
The docs for `useOpenmrsPagination` and `useOpenmrsInfinite` are different though. Do you think that's ok?

2024-09-04 16:56 UTC, mogoodrich commented
> (I find the useSWR documentation confusing on this as well, although we can certainly document our version of it better) If I understand correctly , `useInfinite` allows you do set `size` (the param for the # of pages to load) and it loads pages `0..size`. What it doesn't let you do is skipping to any arbitrary page without loading all pages preceding it, so if you only want to load the page 17, there is no way to do so without also loading pages 0 to 16.

If useSWR is confusing, fair.... in which case you could just (or also) point to the useSWR documentation for the *Pagination and *Infinite methods?

2024-09-04 16:56 UTC, mogoodrich approved these changes

2024-09-04 18:24 UTC, merged

2024-09-04 23:28 UTC, mogoodrich commented on packages/framework/esm-react-utils/src/useFhirInfinite.ts
> + * This function is the FHIR counterpart of `useOpenmrsInfinite`.
Fair enough...