(feature) O3-3859 Ability to customize or add logos at the bottom of the LogIn page below the "Powered by"
openmrs/openmrs-esm-core pull request #1127
Opened 2024-08-27 18:25 UTC by suubi-joshua

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
I added a footer config, to allow specification of logos to be included in the footer.

## Screenshots
[Screencast from 08-27-2024 09:16:33 PM.webm](https://github.com/user-attachments/assets/bda4b97b-f7cd-4b5b-9ea2-098b522b31bf)

## Related Issue

https://openmrs.atlassian.net/browse/O3-3859

## Other

2024-08-27 18:27 UTC, suubi-joshua commented
@ibacher @gracepotma requesting a review here. Not sure why am getting a Network Error.

2024-08-28 15:44 UTC, ibacher commented
It shouldn't be possible to remove the OpenMRS logo from the Powered By slot at all.

2024-08-28 19:39 UTC, suubi-joshua commented
> It shouldn't be possible to remove the OpenMRS logo from the Powered By slot at all.

Noted @ibacher , I removed the conditional rendering. Now the OpenMRS Logo always renders whether there are more logos specified or not in the configs.

[Screencast from 08-28-2024 10:32:55 PM.webm](https://github.com/user-attachments/assets/3a9a6ef7-3ab0-4ca0-baf0-2bbe11ca7aad)

2024-09-10 09:33 UTC, sherrif10 commented on packages/apps/esm-login-app/src/footer.component.tsx
> +        {logos.map((logo, index) => (
Hello @suubi-joshua  Basing on @ibacher suggestion, Does this fixes the issue. i thought this can be generic

2024-09-19 03:03 UTC, sherrif10 commented on packages/apps/esm-login-app/src/config-schema.ts
> +        _properties: {
Hello @suubi-joshua  , Any progress on this as its urgently needed on UVL project

2024-09-19 13:25 UTC, vasharma05 requested changes

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/__mocks__/config.mock.ts
> +        alt: 'Logo',
```suggestion
        alt: '',
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/config-schema.ts
> +      },
AFAIK, it's the `_elements`, instead of `_properties` to define the structure of the array element.

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/footer.component.tsx
> +            alt={logo.alt ? t(logo.alt) : t('poweredByLogo', 'Powered By Logo')}
```suggestion
            alt={logo.alt ? t(logo.alt) : t('logo', 'Logo')}
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.component.tsx
> +            <Footer t={t} />
```suggestion
            <Footer />
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/footer.component.tsx
> +const Footer: React.FC<{ t: TFunction }> = ({ t }) => {
```suggestion
const Footer: React.FC = () => {
  const {t} = useTranslation();
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.scss
> +  gap: 2rem;
Margin as well as gap, we should get rid of gap

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.scss
> +.logosContainer {
```suggestion
.logosContainer::last-of-type {
	margin-right: 0;
}
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.scss
> +@media (min-width: 768px) {
```suggestion
:global(.omrs-breakpoint-gt-phone) {
```

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.scss
> +@media (min-width: 768px) {
Since we don't support mobile devices, we can remove this override.

2024-09-19 13:25 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login/login.scss
> +  margin-bottom: -3.0rem;
Why a negative margin 🤔 ?

2024-10-03 09:09 UTC, suubi-joshua commented
@gracepotma @ibacher @vasharma05 @brandones

2024-10-04 06:37 UTC, suubi-joshua commented
New developments here 
https://openmrs.slack.com/archives/CKS32D55G/p1727938916121129

2024-10-10 16:46 UTC, brandones requested changes
Let's get this in and then we can implement the new designs in another PR. I think the config interface should be able to stay the same anyway. Please also address Vineet's feedback.

2024-10-10 16:46 UTC, brandones commented on packages/apps/esm-login-app/src/footer.component.tsx
> +            src={interpolateUrl(logo.src)}
```suggestion
            src={logo.src}
```

`interpolateUrl` does nothing with no second argument

2024-10-10 16:46 UTC, brandones commented on packages/apps/esm-login-app/src/config-schema.ts
> +    logos: {
```suggestion
    additionalLogos: {
```

Also modify the type element and the mock

2024-10-10 16:46 UTC, brandones commented on packages/apps/esm-login-app/src/config-schema.ts
> +      _description: 'An array of logos to be displayed in the footer.',
```suggestion
      _description: 'An array of logos to be displayed in the footer next to the OpenMRS logo.',
```

2024-10-10 16:46 UTC, brandones commented on packages/apps/esm-login-app/__mocks__/config.mock.ts
> +    ],
```suggestion
    additionalLogos: [],
```

2024-10-10 16:48 UTC, brandones commented on packages/apps/esm-login-app/src/footer.component.tsx
> +          <use href="#omrs-logo-full-color"></use>
```suggestion
          <use href="#omrs-logo-partial-mono"></use>
```

This change should not cause the RefApp defaults to diverge from the designs.

2024-10-10 16:51 UTC, brandones commented
Please fix the CSS so that the styling is unchanged when using defaults. That includes the spacing between "Powered by" and the monochrome OpenMRS logo.

Try and simplify the CSS. I am very mistrustful of the big mess of CSS you have added; I will be surprised if it is not mostly unnecessary.

2024-10-14 11:22 UTC, suubi-joshua commented
I have addressed your requests @brandones 
Though in my new changes I have made all uploaded logos have a grey to align with the O3 design
Before 
![image](https://github.com/user-attachments/assets/1a36bff7-0fc2-4a60-bdde-1337df6b4099)
After
![Screenshot from 2024-10-14 14-10-11](https://github.com/user-attachments/assets/5141cfb2-1b7b-4d53-9c1c-b2239e7aec18)

2024-10-14 13:46 UTC, brandones approved these changes
LGTM. Thanks @suubi-joshua .

2024-10-14 13:48 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.scss
> +.logosContainer {
Hard to tell without seeing the dev tools how the margins are working. If you want to clean it up after the merge, @vasharma05 , you are very welcome, I'll give a quick review. But this has been open a long time already, time to get it in.

2024-10-14 13:49 UTC, merged