(DRAFT) (refactor) O3-4077: Move workspace family to the workspace container
openmrs/openmrs-esm-core pull request #1185
Opened 2024-10-28 06:01 UTC by vasharma05

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
Currently, for the related workspaces (current implementation: patient dashboard workspace in the Ward View), the sidebar family (group of workspaces is termed as a family) is defined in the workspace registration using 2 properties `hasSidebar` and `sidebarFamily`.

@brandones suggests that we can move this handling to the `WorkspaceContainer`, and pass a `familyName/containerName`, which will render the specific family of workspaces only, hence separating the individual workspaces from the family of workspaces.

Additionally, we update the `launchWorkspace` API to support launching a workspace in a family container. I added a 3rd argument in the above function to input the `containerName`/ `familyName`.

## Additional improvements
Currently, we are making this change specific to the patient dashboard workspace in the Ward View, but re-thinking, we can handle the patient chart workspaces on the sidebar (Order Basket, Clinical Forms, Notes workspaces, etc.) as a family of related workspaces too. Moreover, the workspace APIs are/ will mix up enough to get chaotic. Hence, as per my discussion with @denniskigen, we can look forward to a clear approach to cleaning up all APIs.

Hence, I have made this PR as a draft for now, and we can brainstorm here on how we can improve the whole workspace system.

## Screenshots
None

## Related Issue
https://issues.openmrs.org/browse/O3-4077

## Other

2024-10-29 01:21 UTC, chibongho commented
With this change, does it mean that the `workspaceFamily` of a workspace is only defined when we call `launchWorkspace(workspaceName, props, workspaceFamily)`? For example, let's say we have a patient search workspace defined in `esm-patient-search-app`. Can we have the same workspace be launched in different workspace families (such as `service-queue-family` and `ward-family`, depending on which app it's launched from)? 

Also, is there a way to close a all workspaces in a workspace family?

If yes to the above questions, then yeah, I'm generally on board. 

This change is a bit hard for me to review without seeing it in action. If people are on board with this, maybe we can also have a draft for corresponding changes in patient chart or patient management?

2024-10-29 06:35 UTC, vasharma05 commented
> let's say we have a patient search workspace defined in esm-patient-search-app. Can we have the same workspace be launched in different workspace families (such as "service-queues-app-family" and "ward-app-family", depending on which app it's launched from)?

Exactly, we won't have to duplicate workspaces to configure it and to open it in the workspace family, now we use the same workspace either individually or in the workspace family, with minimal to no changes. I am using the same to add Order Basket to the Ward Workspace.

> Also, is there a way to close a all workspaces in a workspace family?

Yes, we have a function to close all workspaces, I need to tweak it to allow closing only the workspaces in a family.

> This change is a bit hard for me to review without seeing it in action. If people are on board with this, maybe we can also have a draft for corresponding changes in patient chart or patient management?

I understand, hence I am implementing this with the order basket addition to the ward workspaces, and will share the results here, currently keeping this PR in draft and will make changes as I find more observations.

Thanks @chibongho for supporting the work!

2024-11-11 09:26 UTC, vasharma05 reviewed
Some notes to myself

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-globals/src/types.ts
> +  workspaceGroups: Array<string>;
Write the JS Doc for `workspaceGroup`

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/container/workspace-container.component.tsx
> +  containerName?: string;
Remove this

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/container/workspace-container.component.tsx
> +        {/* {hasOwnSidebar && <ActionMenu isWithinWorkspace name={workspaceInstance.sidebarFamily} />} */}
Remove this

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspace-sidebar-store/useWorkspaceFamilyStore.ts
> +export function useWorkspaceFamilyStore(sidebarFamilyName?: string) {
Replace sidebarFamilyName with workspaceGroupName

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  closeWorkspaceGroup?: boolean;
Update the JSDoc

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    // Clearing the workspace family store if there are no more workspaces with the same sidebar family name and the new workspace is not of the same sidebar family, which is handled in the `launchWo
Update this

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +export function launchWorkspaceGroup(args: LaunchWorkspaceGroupArg) {
Add JSDoc

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +function closeWorkspaceGroup(groupName: string, onWorkspaceCloseup?: Function) {
Add JSDoc

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  newWorkspaceDetails: { name: string; additionalProps?: object; workspaceContainerName?: string },
Remove `workspaceContainerName`

2024-11-11 09:26 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      // !newOpenWorkspaces.some((w) => w.workspaceContainerName === workspaceSidebarFamilyName)
Remove this comment

2024-11-11 15:49 UTC, brandones commented
As a total aside: looking at this code

```
            onWorkspaceGroupLaunch: () => {
              const store = getPatientChartStore();
              store.setState({
                patientUuid: patient.uuid,
              });
              launchWorkspace<PatientWorkspaceAdditionalProps>('patient-transfer-swap-workspace');
            },
```

I think we should wrap the patient chart state in a higher-level API. Something like `setCurrentPatient` and `getCurrentPatient`.

2024-11-11 15:51 UTC, brandones commented on packages/framework/esm-framework/docs/interfaces/CloseWorkspaceOptions.md
> +Defaults to true except when opening a new workspace of the same family.
I thought `family` is no more? How is a workspace's family set?

2024-11-11 15:52 UTC, brandones commented on packages/framework/esm-routes/src/loaders/components.ts
> +      workspaceGroups: workspace.workspaceGroups ?? [],
"Workspace" is redundant with the context, this can just be `groups`

2024-11-11 15:53 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/container/workspace-container.component.tsx
> +  const { workspaces, workspaceWindowState, workspaceGroup } = useWorkspaces();
With reference to my comment above on `workspaceGroups` vs `groups`, it's ok/good if the API for `useWorkspaces` remains `workspaceGroup` though

2024-11-11 15:57 UTC, brandones commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +        },
We should consider a simpler API for this, if this is the pattern. Like, why would we ever launch a group without launching a workspace at the same time? Perhaps `launchWorkspaceGroup` should take a `workspaceToLaunch` parameter.

2024-11-11 15:59 UTC, brandones commented
I've provided some feedback. I did some pairing with Vineet and Usama on this so it would be great if someone else could review after the next revision. Generally I think the approach is good. @mogoodrich @chibongho @denniskigen @ibacher

2024-11-12 06:17 UTC, vasharma05 commented on packages/framework/esm-framework/docs/interfaces/CloseWorkspaceOptions.md
> +Defaults to true except when opening a new workspace of the same family.
Sorry, family is renamed to group, let me correct this.

2024-11-13 19:06 UTC, chibongho reviewed
Thanks. I think this will simplify the workspace sidebar

Questions: 
- Should a workspace instance have access to its `currentWorkspaceGroup` (since it is required to close its workspace group)?
- When `launchWorkspace` is called from within a workspace or from an action menu item, does the new workspace get launched within the same workspace group?
- Is it still true that a `WorkspaceContainer` is not tied to any particular workspace or workspace group? (so we don't need to create multiple WorkspaceContainer for multiple workspace groups?)
- Tangent. I'm not that comfortable with the idea of `contextKey` for `WorkspaceContainer`, which defines the URL subpath to match on to determine whether any workspaces in the `WorkspaceContainer` should remain open. It feels like we should just close any open workspaces when the `<WorkspaceContainer>` dismounts. Thoughts?

2024-11-18 20:51 UTC, brandones commented
@chibongho thanks for the thoughtful review, much appreciated. Just a note:

> I'm not that comfortable with the idea of contextKey for WorkspaceContainer, which defines the URL subpath to match on to determine whether any workspaces in the WorkspaceContainer should remain open. It feels like we should just close any open workspaces when the <WorkspaceContainer> dismounts. Thoughts?

The reason we designed it this way is because it doesn't always line up well with mounts/unmounts. In particular, when transitioning between different patients in the patient chart, the WorkspaceContainer will not be unmounted; however, any open workspaces should certainly be closed. On the home page, I don't remember whether things like Service Queues are dashboards or independent pages that just happen to be served under the `/home` path, but in the latter case, this would be a thing where the workspace should stay open even though the component would need to unmount.

2024-11-19 07:11 UTC, vasharma05 commented on packages/framework/esm-globals/src/types.ts
> +  groups: Array<string>;
No, the registration of the workspace is the right place to define the groups, else, the developer will have to handle different scenarios of whether to open it in the group or individual, which right now is handled by the workspace system.

2024-11-19 07:11 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +  describe('Testing `getWorkspaceGroupStore` function', () => {
Sure, I'm on it

2024-11-19 07:14 UTC, vasharma05 commented
> * Should a workspace instance have access to its currentWorkspaceGroup (since it is required to close its workspace group)?

Yes, when the `launchWorkspace` is called, the `openWorkspace` stores the group name.

> * When launchWorkspace is called from within a workspace or from an action menu item, does the new workspace get launched within the same workspace group?

If the workspace registration (inside the `routes.json`) defines the current open workspace group inside the workspace's `groups` properties, it will open inside the container, else it will close the workspace group and then open the new workspace.

> * Is it still true that a WorkspaceContainer is not tied to any particular workspace or workspace group? (so we don't need to create multiple WorkspaceContainer for multiple workspace groups?)

Yes, we just need 1 workspace container

2024-11-20 01:25 UTC, vasharma05 commented
Hi @brandones @chibongho ,
Requesting your review here and if all good, may we merge it, given it's needed for some other tasks too.
Thanks!

2024-11-21 03:59 UTC, chibongho commented on packages/framework/esm-globals/src/types.ts
> +  groups: Array<string>;
Ok, I think I misunderstood our earlier conversation. Does that mean that a workspace must have a workspace group defined in `routes.json` for it to be launched in that workspace group? (in other words, it's impossible to create a workspace that can be launched in any arbitrary workspace group.) 

I'm thinking of something like the patient search workspace in `esm-patient-serach-app`, where it's really meant for other apps (ex: `esm-service-queues-app`) to launch it. There is no way to launch the patient search workspace in the "service-queues-app" group, correct? (Admittedly, if we really want this, we can work around it by having the patient search workspace be an extension instead, and slot it into a workspace in the "service-service-app" group defined within `esm-service-queues-app`)

2024-11-21 04:05 UTC, chibongho commented
> Yes, when the `launchWorkspace` is called, the `openWorkspace` stores the group name.

Shouldn't the group name also be accessible in `DefaultWorkspaceProps`? If not, how does a workspace access the group name?

> If the workspace registration (inside the routes.json) defines the current open workspace group inside the workspace's groups properties, it will open inside the container, else it will close the workspace group and then open the new workspace.

Ok, that makes sense.

2024-11-21 10:44 UTC, vasharma05 commented on packages/framework/esm-globals/src/types.ts
> +  groups: Array<string>;
> Admittedly, if we really want this, we can work around it by having the patient search workspace be an extension instead, and slot it into a workspace in the "service-service-app" group defined within esm-service-queues-app

I didn't understand this

2024-11-21 19:02 UTC, chibongho commented
> > Shouldn't the group name also be accessible in DefaultWorkspaceProps? If not, how does a workspace access the group name?
> 
> What's the use case for this? As far as the common data of a group is concerned, all the common data is shared in the workspace props, as previously implemented. Thanks!

Ok, never mind. Your answer to the other question makes this moot. I was thinking something like this:

```
function MyWorkspace(props: DefaultWorkspaceProps) {
  const onSubmit = () => {
     submitData().then(() => closeWorkspaceGroup('myWorkspaceGroup')); 
  }
  return (<button onClick={onSubmit} />);
}
```

But since `MyWorkspace` must be defined with a workspace group (`myWroskpaceGroup`), we should always know what it is without needing to access it programmatically.

2024-11-22 13:41 UTC, ibacher requested changes
Great overall work here, aside from the nit-picking comments I left. 

There's some documentation work to be improved and, since this affects the routes.json file, we should also have a a PR [to update the schema](https://github.com/openmrs/openmrs-contrib-json-schemas/blob/main/routes.schema.json).

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-globals/src/types.ts
> +  groups: Array<string>;
Or just a set of React components, so it can be added to the styleguide? That seems the cleanest to me...

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      onWorkspaceCloseup?.();
We already did the checking that this is defined, so...

```suggestion
      onWorkspaceCloseup();
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      currentWorkspaceGroup?.cleanup?.();
```suggestion
      currentWorkspaceGroup.cleanup();
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    if (currentWorkspaceGroup && typeof currentWorkspaceGroup?.cleanup === 'function') {
You really don't need more than this:

```suggestion
    if (typeof currentWorkspaceGroup?.cleanup === 'function') {
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    if (onWorkspaceCloseup && typeof onWorkspaceCloseup === 'function') {
I think there should be a newline here.

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    if (currentWorkspaceGroup && typeof currentWorkspaceGroup?.cleanup === 'function') {
There should also probably be a newline here...

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      unsubscribe?.();
I think it's safe to assume that `unsubscribe()` is always defined here, no?

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  const currentGroupName = store.getState()?.workspaceGroup?.name;
```suggestion
  const currentGroupName = currentWorkspaceGroup?.name;
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +      launchWorkspace(workspaceToLaunch?.name, workspaceToLaunch?.additionalProps ?? {});
```suggestion
      launchWorkspace(workspaceToLaunch.name, workspaceToLaunch.additionalProps ?? {});
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    closeWorkspaceGroup(currentWorkspaceGroup?.name, () => {
```suggestion
    closeWorkspaceGroup(currentWorkspaceGroup.name, () => {
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  const currentGroupName = store.getState().workspaceGroup?.name;
```suggestion
  const currentGroupName = currentWorkspaceGroup?.name;
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +    });
```suggestion
    .every(({ name }) => canCloseWorkspaceWithoutPrompting(name));
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-globals/src/types.ts
> +  preferredWindowSize?: WorkspaceWindowState;
This needs docs...

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-globals/src/types.ts
> +   * the current group will close and then the workspace will be launched.
I feel like the description here is unclear. Maybe:

```suggestion
   * Workspaces can open either independently or as part of a "workspace group". A
   * "workspace group" groups related workspaces together, so that only one is visible
   * at a time. For example, <USE CASE DESCRIPTION HERE>.
   *
   * In case the currently opened workspace is not present in the groups of a workspace,
   * the current group will close and then the workspace will be launched.
```

2024-11-22 13:41 UTC, ibacher commented on packages/framework/esm-globals/src/types.ts
> +   * the current group will close and then the workspace will be launched.
These last two lines are really ambiguous. Can you think of a way to rephrase it? I'm not entirely sure what this is trying to communicate, so I'm not sure what to suggest.

2024-11-22 13:43 UTC, ibacher commented on packages/framework/esm-globals/src/types.ts
> +   * the current group will close and then the workspace will be launched.
What's unclear to me: What does "currently opened workspace" here mean? Is the workspace being opened, the workspace currently opened, any workspace in the workspace stack? What does this have to do with "launching"?

2024-11-26 18:56 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspace-sidebar-store/useWorkspaceGroupStore.ts
> +export function useWorkspaceGroupStore(workspaceGroupName?: string) {
Since this function was initially made to be called for workspaces launched with and without a group name, the argument is hence optional. If the argument is `undefined`, this function will return `undefined`, else will return a global store.

I have already added tests for this function.

2024-11-26 18:57 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +      expect(workspaceGroupStore?.getState()?.['foo']).toBe(true);
It has become a habit of mine to use null checks, so that I can check things validity, and also it doesn't break the code at any point. I'll try to improve on this.

2024-11-26 18:58 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +function closeWorkspaceGroup(groupName: string, onWorkspaceCloseup?: Function) {
Done

2024-11-26 19:03 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +  const currentGroupName = store.getState().workspaceGroup?.name;
After closing the workspace group, the updated workspace group might have been updated, hence I am fetching the workspace group name from the state.

2024-11-26 19:17 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +export function launchWorkspaceGroup(groupName: string, args: LaunchWorkspaceGroupArg) {
Yes, it makes sense to have a separate `launchWorkspaceGroup` function for the following reasons:

1. Making clear distinction between launching workspace and launching workspace group. Providing different function orderloads will in the end confuse the developer too.
2. `launchWorkspace` function is used for every workspace launch, and on the other hand, `launchWorkspaceGroup` function is used only at the initial launch.

2024-11-27 17:08 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspace-sidebar-store/useWorkspaceGroupStore.ts
> +export function useWorkspaceGroupStore(workspaceGroupName?: string) {
Ok. Can we update the docs to match the code?

2024-11-27 17:23 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.test.ts
> +      expect(workspaceGroupStore?.getState()?.['foo']).toBe(true);
The only reason I bring this up is because of how it gets compiled. Specifically, since the optional operator isn't supported across browsers, e.g.,

```ts
store?.getState()?.['option']
```

Gets can get compiled into this gnarly mess:

```js
var _store_getState, _store;
(_store = store) === null || _store === void 0 ? void 0 : (_store_getState = _store.getState()) === null || _store_getState === void 0 ? void 0 : _store_getState['option'];
```

Which is semantically the same, but which involves 3 branching statements and 2 comparisons per branch ("native" support for `?`, this is pushed into the interpreter itself, which is usually faster).

2024-11-27 17:38 UTC, vasharma05 commented on packages/framework/esm-globals/src/types.ts
> +   * the current group will close and then the workspace will be launched.
Updated the doc here

2024-11-27 18:08 UTC, ibacher commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +export function launchWorkspaceGroup(groupName: string, args: LaunchWorkspaceGroupArg) {
Are clients expected to call both of these functions? When would I, as a code consumer, call `launchWorkspaceGroup()` instead of `launchWorkspace()`?

2024-11-27 20:24 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/workspaces/workspaces.ts
> +export function launchWorkspaceGroup(groupName: string, args: LaunchWorkspaceGroupArg) {
No, to launch the workspace group, the client only needs to call the `launchWorkspaceGroup` function and they can pass the new workspace's details into the argument. You can refer to the argument structure [here](https://github.com/openmrs/openmrs-esm-core/blob/deb79bde7e9b17a9eabe186bd23ea607f04525ad/packages/framework/esm-styleguide/src/workspaces/workspaces.ts#L182).
Thanks!

2024-12-02 13:45 UTC, vasharma05 commented
Hi @ibacher!
Please note that this PR is not a breaking change at all. It doesn't change any existing workspace API/ functionality, just add improvements for workspace groups.
Thanks!

2024-12-11 18:39 UTC, ibacher approved these changes

2024-12-11 18:39 UTC, merged