(feat) O3-4100 - Login page UI enhancement.
openmrs/openmrs-esm-core pull request #1192
Opened 2024-10-30 22:34 UTC by suubi-joshua

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary 
I have basically tried to implement the designs drafted by Ciaran for the login page the designs can be seen via the linked ticket. What I have done is to create a carbon tile in the footer to house the wording in the openmrs logo, also a button that links to the openmrs website. I also moved the logos container to the right bottom of the screen. 
There was a suggestion by Ciaran to render password field after validating username but this may pose a security threat as discussed[ here ](https://openmrs.slack.com/archives/C02UNMKFH8V/p1730231447550219). But I have still enabled conditional rendering ie the password field renderson the same screen when user inputs username and clicks the continue button. 
Also because of the additons in the footer I have tried to make sure that the elements are responsive on different screens.

## Screenshots
![Screenshot from 2024-10-30 22-16-27](https://github.com/user-attachments/assets/570d114c-93a4-46bd-9f32-97ccc064ae53)

![Screenshot from 2024-10-30 22-16-39](https://github.com/user-attachments/assets/c52d0b90-5a1f-41c3-ad6a-bb8e21307e26)

Video
[Screencast from 30-10-24 22:15:19.webm](https://github.com/user-attachments/assets/da1f9849-097e-4c6d-ba69-06f8fcbfd8be)

## Related Issue

https://openmrs.atlassian.net/browse/O3-4100

## Other

2024-10-31 18:16 UTC, suubi-joshua commented
@denniskigen & @gracepotma 
I have tried to do the designs suggested by Ciaran.

2024-11-18 21:22 UTC, brandones commented
Hi @suubi-joshua , please fix the tests. CI is failing.

Great description on this PR though, that's very helpful and clear!

2024-11-19 18:17 UTC, suubi-joshua commented
@brandones Thanks for the review fixed the failures. The config for `showPasswordOnSeparatescreen` was not working when set to `false` ie both password and username fields showing on same screen. 
But now its all working well cc: @denniskigen 
[Screencast from 19-11-24 21:11:07.webm](https://github.com/user-attachments/assets/82c75889-b24c-411b-b11b-76fcdcafef9e)

2024-11-22 16:14 UTC, ibacher requested changes
So, I think the styling is fine, but it seems like this PR introduces functional regressions in the login app, which need to be fixed.

2024-11-22 16:14 UTC, ibacher commented on packages/apps/esm-help-menu-app/src/help-menu/help.component.tsx
> +      {user && (
I'm not sure I understand why we've added this restriction? Seems both unrelated and like we may want the opportunity for implementers to show the HelpMenu on the login screen.

2024-11-22 16:14 UTC, ibacher commented on packages/apps/esm-login-app/src/login/login.component.tsx
> -  if (!loginProvider || loginProvider.type === 'basic') {
I'm a little concerned about removing this since the support for other loginProviders is a feature that now seems to be removed?

2024-11-22 16:14 UTC, ibacher commented on packages/apps/esm-login-app/src/login/login.component.tsx
> -      navigate('/login/confirm');
It seems like the loss of `navigate()` results in a regression in functionality where the username and password are displayed on separate "screens", but if I mess up entering my user name and click continue, I can now no longer go back to fix that.

2024-11-23 18:09 UTC, suubi-joshua commented on packages/apps/esm-help-menu-app/src/help-menu/help.component.tsx
> +      {user && (
@ibacher sorry about this, I dont know why this is showing up as a change cause it is related to [this](https://github.com/openmrs/openmrs-esm-core/pull/1186) if the help button appears in that position it blocks the logos. 
Yes this is unrelated to this but not sure why it showing as a change since its already part of core.

2024-12-03 20:22 UTC, ibacher commented on packages/apps/esm-login-app/src/login/login.component.tsx
> -      navigate('/login/confirm');
I see. Ok. I wasn't looking at the redesigned screen.

2024-12-11 18:42 UTC, ibacher commented on packages/apps/esm-login-app/src/login/login.component.tsx
> +export default Login;
```suggestion
export default Login;

```

2024-12-11 18:43 UTC, ibacher approved these changes

2024-12-15 17:00 UTC, brandones commented
E2E failure in patient chart appears unrelated.

2024-12-15 17:01 UTC, merged