Mf 674
openmrs/openmrs-esm-core pull request #162
Opened 2021-08-09 08:16 UTC by alexkemboi4127

### Description
Made enhancement to the user icon on the navigation bar.
[Link to the issue](https://issues.openmrs.org/projects/MF/issues/MF-674?filter=allopenissues)

2021-08-09 08:54 UTC, donaldkibet requested changes

2021-08-09 08:54 UTC, donaldkibet commented on packages/apps/esm-primary-navigation-app/src/components/navbar/navbar.component.tsx
> +              style={{ padding: "12px", background:isActivePanel("userMenu") ? '#004144':'' }}
1. This colour is already included in our styleguide [here](https://github.com/openmrs/openmrs-esm-core/blob/d28d7d031103a558516822465a6cc8a4322fb067/packages/framework/esm-styleguide/src/_vars.scss#L24) I believe this is `$brand-02` use this variable instead of hard coding the colour value.
2. Avoid using inline style instead make use of class.

2021-08-16 15:42 UTC, brandones commented
![Screenshot from 2021-08-16 08-42-11](https://user-images.githubusercontent.com/1031876/129590923-6908423d-003c-48e6-991e-998576b865d0.png)

Looks like you still need to run Prettier, @alexkemboi4127

2021-08-17 09:36 UTC, donaldkibet approved these changes
LGTM! Thanks @alexkemboi4127

2021-08-17 09:39 UTC, merged