(bug) fix login not displaying invalid login message
openmrs/openmrs-esm-core pull request #292
Opened 2022-01-25 19:22 UTC by donaldkibet

## Requirements

- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

## Summary

- When a user logs in with bad password, no error message is displayed. 

## Screenshots

![bug-login](https://user-images.githubusercontent.com/28008754/151044882-ec634590-3a0e-46ac-a377-d3bfca69d524.gif)

## Related Issue

_None._

## Other

_None._

2022-01-25 23:54 UTC, jonathandick approved these changes
lgtm

2022-01-26 01:18 UTC, brandones commented on packages/apps/esm-login-app/translations/en.json
> -  "errorMessage": "",
Ha! This would explain why the text never showed up in English.

2022-01-26 01:18 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.tsx
> -            </div>
And the fact that nothing wraps this would explain why it *always* shows up for languages with a non-blank translation.

2022-01-26 01:34 UTC, brandones requested changes
@donaldkibet Going to disagree with JJ here. There are now two competing mechanisms for handling errors—the existing one, and the one you created. The original is quite good and I think we should use it, though it needs a little repair.

What it does is throws an Error for the invalid credentials (line 108), then handles that Error—_or any other error, such as a 5XX_—in a catch block. Whatever the error, its message goes to `errorMessage` (line 111) and the inputs get reset (line 112).

Where things go wrong is on line 214, where the translation key is used. Right now, the line is

```tsx
t("errorMessage", errorMessage)
```

This will look up a translation key "errorMessage" and print it if it finds it, and print `errorMessage` only if no translation key is found—but it is always found, so it is always printed. In English it is `""` so nothing is printed. In Spanish the error text is always shown.

I think the intention of the author was probably

```
t(errorMessage, errorMessage)
```

This should print nothing if `errorMessage` is empty, a translation if `errorMessage` happens to be equal to one of the translation keys, and otherwise will print `errorMessage` itself.

We should change line 108 so that it throws something that looks more like a translation key so that the intent of the code is clearer:

```tsx
throw new Error("invalidCredentials")
```

And then make sure that `invalidCredentials` is defined as a translation key in all the translation JSON files. If we are doing automatic extraction, we may need to find a way to tell it about this key.

2022-01-26 01:36 UTC, brandones commented
Note that in the code you've written, `errorMessage` is never used. And no matter the error that comes up (even e.g. a 503), "Invalid username or password" is what gets printed, which is not good.

2022-01-26 01:40 UTC, brandones commented
See the [i18next-parser README](https://github.com/i18next/i18next-parser#caveats) about the dynamic keys. Looks like we will want something like

```js
// t('invalidCredentials')
```

2022-01-26 16:21 UTC, donaldkibet commented
@brandones I have made the requested changes

2022-01-26 16:44 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.tsx
> +            subtitle={t(`${errorMessage}`)}
```suggestion
            subtitle={t(errorMessage)}
```

2022-01-26 16:47 UTC, brandones approved these changes
One suggestion, but otherwise looks good! Thanks @donaldkibet .

2022-01-26 17:58 UTC, donaldkibet commented
Thanks @brandones for the review, going ahead and merging this in

2022-01-26 17:59 UTC, merged