O3-104: Fix Login ESM should have tests for config values
openmrs/openmrs-esm-core pull request #323
Opened 2022-02-11 14:12 UTC by nanfuka

## Requirements
- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [ ] My work includes tests, or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

## Other

2022-02-11 16:53 UTC, brandones requested changes

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +jest.mock("@openmrs/esm-framework", () => {
There's already a mechanism for mocking the config, as is seen in the file you yourself linked to yesterday: https://github.com/openmrs/openmrs-esm-core/blob/master/packages/apps/esm-login-app/src/choose-location/choose-location.component.test.tsx . Please use that.

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +  it("the logo svg gets swapped out for an img with the right src when logo.src != null and also the logo alt text gets set correctly when logo.alt != null && logo.src != null", () => {
```suggestion
  it("the logo svg gets swapped out for an img with the right src when logo.src != null and also the logo alt text gets set correctly when logo.alt != null && logo.src != null", () => {
```
```suggestion
  it("respects the logo configuration", () => {
```

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +        match={undefined}
```suggestion
```

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +jest.mock("@openmrs/esm-framework", () => {
Also using that mechanism will allow you to put the config value in the test that it pertains to.

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +    expect(logo).toHaveAttribute("alt");
Also check the `src`

2022-02-11 16:53 UTC, brandones commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +    expect(logo).toHaveAttribute("alt");
Since you got the logo by the alt text, it is redundant to check if it has attribute `alt`.

2022-02-14 06:40 UTC, nanfuka commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +jest.mock("@openmrs/esm-framework", () => {
interpolateUrl is not defined in the current context. so am mocking @openmrs/esm-framework/mock, which makes the two situations different. using the mechanism you are suggesting might not bring the expected output. @brandones

2022-02-14 07:02 UTC, nanfuka commented on packages/apps/esm-login-app/src/login/login.component.test.tsx
> +        match={undefined}
Are suggesting I do away with line 175 and 176... if so they are Login properties which I cant do away with

2022-02-14 19:40 UTC, brandones commented
@nanfuka , this change is not sufficiently useful to warrant the time required to mentor you.

2022-02-14 19:40 UTC, closed without merging