O3-1145: Person attribute labels should be loaded from the backend
openmrs/openmrs-esm-core pull request #346
Opened 2022-03-07 12:57 UTC by vasharma05

This PR is an extension to #325.
## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
In the work done in #325, the user can fetch the UUID of the person-attribute-type from the backend but filled the name of the attribute-type manually. In this PR, I have made changes such that when a user fetches the attribute type by UUID from the backend, the name field will also be filled from the backend's response.

## Screenshots
Uploading Loom _ Free Screen & Video Recording Software - 7 March 2022.mp4…

## Related Issue
https://issues.openmrs.org/browse/O3-1143

## Other

2022-03-07 17:44 UTC, vasharma05 commented
Hi @ibacher!
I was a bit concerned about the new change. I had to change 2 fields(name and UUID) from a single input, hence I thought of adding all the fields in the person-attribute's search component in the implementor tools, as is done in packages/apps/esm-implementer-tools-app/src/configuration/value-editors/person-attribute-search.tsx. I just wanted to know if there'll be any fallout of this method in the future?
Thanks!

2022-03-07 17:52 UTC, ibacher commented
@vasharma05 I think that in light of [O3-1143](https://issues.openmrs.org/projects/O3/issues/O3-1143), I think it would be better if we refactored things to just not capture the name for the attribute type field at all or at least not as a separate element. Instead, we can change things so that this works very similar to how the `ConceptSearchBox` component already works, i.e., we're searching based on name, but storing a UUID value.

The rationale being that way we can load the attribute type name in the current user's locale rather than the implementors locale.

2022-03-07 21:19 UTC, ZacButko requested changes
Code looks OK, but I agree with @ibacher we should store UUID instead of name. We should also fix the missing useEffect dependency before mergin.

2022-03-07 21:19 UTC, ZacButko commented on packages/apps/esm-implementer-tools-app/src/configuration/value-editors/value-editor-field.tsx
> +        onChange(personAttributeType)
This can be reduced to `setPersonAttributeUuid={onChange}`

2022-03-07 21:19 UTC, ZacButko commented on packages/apps/esm-implementer-tools-app/src/configuration/value-editors/person-attribute-search.tsx
> +                  handleChange("name", personAttributeType.display);
This does two synchronous updates, which also calls resetSearch twice. In this case it doesn't look like it will cause many re-renders, but in more complex cases it could be noticeable. Your `handleChange` function could be restructured as below in order to handle updating multiple keys at the same time

`handleChange() = newData -> {
   setAttributes((prevAttributes) => ({
     ...prevAttributes,
     ...newData
   })
)`

2022-03-08 19:06 UTC, vasharma05 commented
After a talk with @ibacher, the requirements for ticket O3-1143 were different than the work done in this PR, hence I am closing this PR. 
I thank the developers to devote their time reviewing this PR.

2022-03-08 19:06 UTC, closed without merging