03 1169
openmrs/openmrs-esm-core pull request #408
Opened 2022-04-25 12:11 UTC by joachim-junior

## Requirements
- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This Issue was aimed and changing the theme of the implementer tools app to dark. I also adjusted some little styling like config buttons for example.
## Screenshots
https://user-images.githubusercontent.com/40958761/165086353-b8db0cef-213c-45dc-ac05-1a5ab71fdd8c.mp4

## Related Issue
[O3-1149](https://issues.openmrs.org/browse/O3-1169)

## Other

2022-04-25 12:38 UTC, vasharma05 commented
Hi @joachim-junior!
Good work, somethings I have noticed are:

1. The hover on the package name doesn't change the text color to black, hence there's a problem reading it.
2. I can't see the edit and revert icons along with the values in the new design.

Please have a look at it.
Thanks!

2022-04-25 12:45 UTC, vasharma05 requested changes
Hey @joachim-junior!
The color theme is not at all in compliance with the designs.
Please refer to the designs in the link: https://wiki.openmrs.org/display/projects/Implementer+Tools+UI+-+Project+Plan.

Please have a look at the designs provided on the page.

2022-04-25 12:49 UTC, vasharma05 requested changes

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/src/backend-dependencies/backend-dependencies.styles.scss
> +  background-color: #000;
Please use variables from "~@openmrs/esm-styleguide/src/vars"

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/src/configuration/configuration.component.tsx
> +                    <p style={{ color: "#efefef" }}>{"Search configuration"}</p>
Please do not use inline styling.

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/src/configuration/configuration.component.tsx
> +                    <p style={{ color: "#efefef" }}>
No inline styling please.

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/src/configuration/configuration.component.tsx
> +                  className={styles.btn}
Please provide more explicit class names.,

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/src/configuration/json-editor/json-editor.component.tsx
> +// import { JsonEditor as Editor } from "jsoneditor-react";
Please remove the comments

2022-04-25 12:49 UTC, vasharma05 commented on packages/apps/esm-implementer-tools-app/webpack.config.js
> +//   module: {
Please remove the comments

2022-04-28 14:22 UTC, joachim-junior reviewed
I have added some colors in the esm-style-guide in accordance with design of implementer tools 2.0.

2022-05-03 09:05 UTC, vasharma05 commented
@joachim-junior, can you please upload a video showing all the latest changes.

2022-05-05 09:34 UTC, joachim-junior commented
https://user-images.githubusercontent.com/40958761/166897421-c2d425cf-7e97-4a56-aa08-b1e00d031239.mp4

2022-05-09 16:13 UTC, brandones commented
For anyone else reading in the future: the above MP4 video displays correctly in Chrome, not Firefox.

@joachim-junior Did you look at the designs? Your implementation looks nothing like them. I attached a PNG of the design to [the ticket](https://issues.openmrs.org/browse/O3-1169).

2022-06-21 16:54 UTC, closed without merging