(BREAKING) Upgrade to Carbon v11
openmrs/openmrs-esm-core pull request #437
Opened 2022-05-23 12:30 UTC by denniskigen

## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR contains a compendium of work aimed at migrating our codebase from version 10 to version 11 of the Carbon design system. This PR:

- Removes the `@carbon-components`,  `@carbon-components-react` and `@carbon-icons`, replacing them with the new `@carbon/react` package. Additionally, it gets rid of `@types/carbon-components-react`, as v11 does not ship with typings yet.
- Replaces all occurrences of the old `bx--` prefix with the new `cds--` prefix. All the styles in v11 are prefixed with `cds--`.
- Migrates all component and icon imports from `carbon-components-react` to `@carbon/react`. Icons are now namespaced under `@carbon/react/icons`.
- Updates colour and type tokens.
- Updates stylesheet import paths.
- Updates components to handle deprecations and changed props.
- Refactors some stylesheets to match our naming convention (*.component.scss -> *.scss).
- Reorganizes some imports to improve readability.
- Provides fixes for some tests.
- Provides some design fixes for the ContentSwitcher component.

2022-05-24 19:46 UTC, brandones requested changes
Awesome work @denniskigen . Just a few things to fix up.

2022-05-24 19:46 UTC, brandones commented on .eslintrc
> +            "message": "Import from `carbon-components-react`. e.g. `import { Toggle } from '@carbon/react'`"
```suggestion
            "message": "Import from `@carbon/react` directly. e.g. `import { Toggle } from '@carbon/react'`"
```

2022-05-24 19:46 UTC, brandones commented on .eslintrc
> +            "message": "Import from `@carbon/icons-react/es`. e.g. `import { ChevronUp } from '@carbon/icons-react'`"
```suggestion
            "message": "Import from `@carbon/icons-react`. e.g. `import { ChevronUp } from '@carbon/icons-react'`"
```

2022-05-24 19:46 UTC, brandones commented on .eslintrc
> +            "group": ["@carbon/react/lib/*"],
Should we add one of these rules to tell people to switch off of `carbon-components-react`?

2022-05-24 19:46 UTC, brandones commented on packages/apps/esm-implementer-tools-app/src/configuration/configuration.test.tsx
> +  it.only("renders the configuration component inside the implementer tools panel", () => {
Let's use [describe.skip](https://jestjs.io/docs/api#describeskipname-fn) instead. And add `TODO` to the comment text.

2022-05-24 19:46 UTC, brandones commented on packages/apps/esm-implementer-tools-app/src/configuration/interactive-editor/value-editor.tsx
> +          renderIcon={(props) => <Save {...props} size={16} />}
Bummer about this new syntax...

2022-05-24 19:46 UTC, brandones commented on packages/apps/esm-primary-navigation-app/src/components/navbar-header-panels/side-menu-panel.component.tsx
> +
What's this about? Can we delete it if it's dead code?

2022-05-24 19:46 UTC, brandones commented on packages/apps/esm-primary-navigation-app/src/components/navbar-header-panels/user-menu-panel.component.tsx
> +const UserMenuPanel: React.FC<any> = ({
Please give this some non-`any` type

2022-05-24 20:00 UTC, denniskigen commented on .eslintrc
> +            "group": ["@carbon/react/lib/*"],
Yeah, sounds good. I'd appreciate it if you could craft the rule and just share it with me.

2022-05-24 20:02 UTC, denniskigen commented on packages/apps/esm-implementer-tools-app/src/configuration/interactive-editor/value-editor.tsx
> +          renderIcon={(props) => <Save {...props} size={16} />}
It allegedly brings about significant savings in terms of bundle size.

2022-05-24 20:10 UTC, denniskigen commented on .eslintrc
> +            "group": ["@carbon/react/lib/*"],
Updated.

2022-05-24 22:37 UTC, brandones commented on .eslintrc
> +            "message": "Import from `@carbon/react/icons`. e.g. `import { ChevronUp } from '@carbon/react/icons'`"
In the code you're using `@carbon/icons-react`?

2022-05-24 22:39 UTC, brandones commented on .eslintrc
> +            "message": "Import from `@carbon/icons-react/es`. e.g. `import { ChevronUp } from '@carbon/icons-react'`"
In the code you're using `@carbon/icons-react`

2022-05-25 08:18 UTC, denniskigen commented on .eslintrc
> +            "message": "Import from `@carbon/icons-react/es`. e.g. `import { ChevronUp } from '@carbon/icons-react'`"
Fixed.

2022-05-25 15:44 UTC, merged