O3-1294:User should be able to navigate back to username screen
openmrs/openmrs-esm-core pull request #449
Opened 2022-06-02 23:57 UTC by jwnasambu

## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
A user is able to navigate from the password input screen to the username input screen to modify their username. 

## Screenshots

https://user-images.githubusercontent.com/33891016/171759709-c9280d16-1011-40af-ac41-0f0f354e8ff4.mp4

## Related Issue

## Other

2022-06-03 06:26 UTC, CynthiaKamau commented
LGTM!

2022-06-06 13:50 UTC, denniskigen reviewed
Nice work, @jwnasambu. I've left a few suggestions.

2022-06-06 13:50 UTC, denniskigen commented on packages/apps/esm-login-app/src/login/login.component.tsx
> +              iconDescription="Back"
```suggestion
              iconDescription="Back to username"
```

2022-06-06 13:50 UTC, denniskigen commented on packages/apps/esm-login-app/src/styles.scss
> +  padding: 13px 3px 17px 0;
```suggestion
  height: 3rem;
```

The `width`, `margin` and `padding` values can be omitted in this case.

2022-06-06 16:56 UTC, jwnasambu commented on packages/apps/esm-login-app/src/styles.scss
> +  padding: 13px 3px 17px 0;
@denniskigen omitting `width`, `margin` and `padding` values  changes the design provided on this link https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/6220c7c1f6a5775abf7846ef. to something like thi
![Screenshot 2022-06-06 at 7 54 18 PM](https://user-images.githubusercontent.com/33891016/172208468-9c6e9c6f-66ea-4123-8394-4159dc93fb10.png)
s

2022-06-06 18:54 UTC, denniskigen requested changes
Please use a different commit message for fixing up the work.

2022-06-06 18:54 UTC, denniskigen commented on packages/apps/esm-login-app/src/styles.scss
> +}
```suggestion
.back-button {
  height: 3rem;
  
  svg {
    margin-right: 0.5rem;
  } 
}
```

2022-06-06 18:54 UTC, denniskigen commented on packages/apps/esm-login-app/src/styles.scss
> +}
Please delete the commented out styles. Also, you could apply a right margin to the SVG arrow icon as shown above. You should not need to remove the background colour of the button on hover - Carbon's default styles handle that just fine.

2022-06-07 12:22 UTC, denniskigen approved these changes

2022-06-07 12:23 UTC, merged