Enhancing UserHasAccess component
openmrs/openmrs-esm-core pull request #472
Opened 2022-07-01 12:31 UTC by Arjun-Go

## Requirements
- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

#### For changes to apps
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

#### If applicable
- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
Existing UserHasAccess component returns null when the user is unauthorised. In this PR, we have enhanced the component such that the user sees an error message / notification or can redirect to a given URL.  

## Screenshots
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91885483/176894861-9a3993a6-2810-4277-8f45-b8df3b70b6a5.png">

2022-07-01 13:20 UTC, manuelroemer commented
Hey @Arjun-Go, thanks for the PR! I think that this concrete approach can potentially cause unwanted side-effects because it is making the component do too much/make too many assumptions about what the unauthorized fallback should look like. Consider that `UserHasAccess` can be used anywhere - both for wrapping entire pages, but also only small sections, e.g. little input fields. If one page used that component 10 times (e.g. for various little form fields), you'd get 10 error messages when the page loads (given that you don't have the required privileges).

I think that, to achieve your goal of rendering some kind of fallback when a user doesn't have access, it would be much better to leave that fallback as a placeholder, e.g. like this (treat the following code as a suggestion, not the ultimate way it should look like):

```tsx
const fallbackWhenUnauthorized = (
    <div className="omrs-inline-notifications-container">
        <InlineNotification
            title="Unauthorised"
            subtitle="You cannot access this page."
            kind="error"
        />
    </div>
);

// Then somewhere else:
<UserHasAccess unauthorizedChildren={fallbackWhenUnauthorized} ...otherProps />
```

Moving the responsiblity to the user of the component keeps `UserHasAccess` clean and lean while also allowing each user to determine the best fallback content to render in that specific situation.

2022-07-04 10:20 UTC, Arjun-Go commented
Hi @manuelroemer, the suggestion really helped. I've refactored the code to incorporate your comments. Thanks!!

2022-07-07 17:22 UTC, brandones requested changes

2022-07-07 17:22 UTC, brandones commented on packages/framework/esm-react-utils/src/UserHasAccess.tsx
> +interface UserHasAccessProps {
This should still be exported

2022-07-07 17:22 UTC, brandones commented on packages/framework/esm-react-utils/src/UserHasAccess.tsx
> +  unauthorisedResponse?: React.ReactNode | undefined;
`response` doesn't make sense as a name here. It's not a response, it's a thing to render. I suggest `fallbackChildren`. Or just `fallback`. Note that `| undefined` is in most cases redundant with `?:`. Also, as an aside, we normatively use US spelling.

2022-07-07 17:22 UTC, brandones commented on packages/framework/esm-react-utils/src/UserHasAccess.tsx
> +  unauthorisedResponse?: React.ReactNode | undefined;
```suggestion
  fallback?: React.ReactNode;
```

2022-07-11 06:20 UTC, Arjun-Go commented on packages/framework/esm-react-utils/src/UserHasAccess.tsx
> +  unauthorisedResponse?: React.ReactNode | undefined;
sure @brandones , changes have been made accordingly.

2022-07-11 16:57 UTC, brandones approved these changes

2022-07-11 17:41 UTC, merged