[MF-371] Report missing backend dependencies to Admin users
openmrs/openmrs-esm-core pull request #50
Opened 2020-12-14 23:07 UTC by samuelmale

Ticket: https://issues.openmrs.org/browse/MF-371

2020-12-18 12:22 UTC, nmalyschkin requested changes
Great job! The tests really help with the `parseUnresolvedDeps` function!

2020-12-18 12:22 UTC, nmalyschkin commented on packages/esm-implementer-tools-app/package.json
> +    "@openmrs/esm-styleguide": "^3.1.7",
`"@openmrs/esm-styleguide"` is in dependecies and devDependencies

2020-12-18 12:22 UTC, nmalyschkin commented on packages/esm-implementer-tools-app/src/backend-dependencies/backend-dependecies.component.tsx
> +                        <TableCell>{undefined}</TableCell>
delete the `{undefined}`

2020-12-18 12:22 UTC, nmalyschkin commented on packages/esm-implementer-tools-app/src/backend-dependencies/backend-dependecies.component.tsx
> +                          )}
This would be cleaner
```jsx
<TableCell>
    {dep.type === "missing" ? (
        <span style={{ color: "red" }}>Missing</span>
    ) : (
        dep.installedVersion
    )}
</TableCell>
```

2020-12-21 10:57 UTC, samuelmale commented on packages/esm-implementer-tools-app/package.json
> +    "@openmrs/esm-styleguide": "^3.1.7",
Yes, because it ships/bundled in the app-shell

2020-12-21 14:27 UTC, samuelmale commented on packages/esm-implementer-tools-app/src/backend-dependencies/backend-dependecies.component.tsx
> +                        <TableCell>{undefined}</TableCell>
@nmalyschkin Resolved

2020-12-21 14:27 UTC, samuelmale commented on packages/esm-implementer-tools-app/src/backend-dependencies/backend-dependecies.component.tsx
> +                          )}
Resolved

2020-12-21 16:25 UTC, nmalyschkin commented on packages/esm-implementer-tools-app/package.json
> +    "@openmrs/esm-styleguide": "^3.1.7",
What I mean is that it should not be in `dependecies` and `devDependecies ` in the same package.json

2020-12-21 16:26 UTC, nmalyschkin approved these changes
Really good work Samuel! Keep it up!

2020-12-29 20:58 UTC, merged