Various Enhancements
openmrs/openmrs-esm-core pull request #59
Opened 2021-01-22 23:35 UTC by FlorianRappl

Just a few things that accumulated over time ...

1. Improved config of the app shell regarding the `spaPath` (now has 0 artifacts *after* the build, i.e., can still be fully configured at runtime)
2. Added ability to specify configuration URLs which are then automatically loaded and provided to the config system
3. Included basic logic for breadcrumbs
4. Added "core UI components" (which are extensions); first of these is an extension to display the breadcrumbs (right now this is a draft implementation that is rather static; to be determined fully later...)

2021-01-23 03:09 UTC, brandones commented on packages/esm-app-shell/src/ui/index.ts
> +      load: getAsyncLifecycle(() => import("./breadcrumbs"), options),
Should be `getAsyncExtensionLifecycle`

2021-01-23 05:21 UTC, brandones commented on packages/esm-api/src/breadcrumbs/filter.ts
> +  return undefined;
Nit: I think `null` would make more sense and be more idiomatic here.

2021-01-23 05:37 UTC, brandones commented on packages/esm-api/src/breadcrumbs/types.ts
> +   * In case of a string it uses the path to regexp result of the given matcher.
This could be clarified a bit.

```suggestion
   * A string or RegEx that determines whether the breadcrumb should be displayed.
   * It is tested against the current location's path.
   * 
   * If `matcher` is a string, it can contain route parameters. e.g. `/foo/:bar`.
   *
   * Can be omitted; the value of `path` is used as the default value.
```

2021-01-23 05:42 UTC, brandones commented on packages/esm-app-shell/src/ui/breadcrumbs.tsx
> +  const breadcrumbs = getBreadcrumbsFor(path);
This is probably fine, since this probably won't re-render often at all? But the other way you could implement it would be to create an "output store" containing just the list of breadcrumbs that should be shown for that location, which gets updated by a `popstate` event listener.

2021-01-23 05:44 UTC, brandones requested changes
Generally looks great. Really excited to try out the config url mechanism.

The only blocker I think is using `getAsyncExtensionLifecycle`.

2021-01-23 16:35 UTC, FlorianRappl commented on packages/esm-app-shell/src/ui/index.ts
> +      load: getAsyncLifecycle(() => import("./breadcrumbs"), options),
Hm is this already fully decided? Sorry was not available in my codebase.

Personally, again, I'd prefer simplicity here and have a single mechanism. I still don't understand why we need to distinguish.

2021-01-23 16:36 UTC, FlorianRappl commented on packages/esm-api/src/breadcrumbs/filter.ts
> +  return undefined;
Why? You should never use `null` (exception: when an API expects this, e.g., React when not rendering something from a component). `undefined` is the way to communicate nothing is returned, `null` is reserved for native APIs.

2021-01-23 16:37 UTC, FlorianRappl commented on packages/esm-app-shell/src/ui/breadcrumbs.tsx
> +  const breadcrumbs = getBreadcrumbsFor(path);
See description of the PR:

> right now this is a draft implementation that is rather static; to be determined fully later...

2021-01-23 16:38 UTC, FlorianRappl commented on packages/esm-app-shell/src/ui/breadcrumbs.tsx
> +  const breadcrumbs = getBreadcrumbsFor(path);
Note the word `static` -> its not meant to rerender at the moment as I first want to see use cases and then see how it works together with different routing mechanism (top-level single SPA vs React's router -> usually all should be covered by the DOM's history API as you mentioned, but I am not 100% sure yet).

2021-01-25 19:29 UTC, brandones approved these changes
LGTM! Thanks!

2021-01-25 19:29 UTC, merged