Add shared logic for fetching patient photo
openmrs/openmrs-esm-core pull request #64
Opened 2021-02-16 20:22 UTC by samuelmale

2021-02-16 20:53 UTC, FlorianRappl requested changes

2021-02-16 20:53 UTC, FlorianRappl commented on packages/esm-api/src/shared-api-objects/current-patient.ts
> +  const { concepts } = await getConfig("@openmrs/esm-patient-registration-app");
No. Don't make some helper libraries dependent on any microfrontend!

2021-02-16 20:53 UTC, FlorianRappl commented on packages/esm-api/src/shared-api-objects/current-patient.ts
> +  const { concepts } = await getConfig("@openmrs/esm-patient-registration-app");
If you really want the concepts to be defined elsewhere then expect this here as an argument.

2021-02-17 08:13 UTC, samuelmale commented on packages/esm-api/src/shared-api-objects/current-patient.ts
> +  const { concepts } = await getConfig("@openmrs/esm-patient-registration-app");
Thanks Florian, closing this PR since extensions will solve this problem.

2021-02-17 08:13 UTC, closed without merging