(test) O3-2113 : Setup playwright and add login e2e test
openmrs/openmrs-esm-core pull request #740
Opened 2023-07-31 11:07 UTC by RandilaP

## Requirements
- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
The Goal of this PR is to setup the core repository for E2E testing with playwright and add login and Logout E2E test

## Screenshots
<img width="1164" alt="image" src="https://github.com/openmrs/openmrs-esm-core/assets/106733522/02bbb633-432d-4b5c-a3d6-299b01a0878c">

## Related Issue

https://issues.openmrs.org/browse/O3-2113

## Other

2023-07-31 11:07 UTC, RandilaP commented
@Piumal1999 @jayasanka-sack Could you please review this

2023-08-05 09:49 UTC, RandilaP commented
@anjula-sack @Piumal1999 @jayasanka-sack Could you please run the workflows

2023-08-07 07:45 UTC, RandilaP commented
@anjula-sack @Piumal1999 @jayasanka-sack Could you please approve approve the workflow

2023-08-07 09:09 UTC, anjula-sack requested changes
@RandilaP This should be ignored

2023-08-07 09:43 UTC, RandilaP commented
@anjula-sack Could you please approve the workflow

2023-08-07 15:41 UTC, anjula-sack commented on e2e/storageState.json
> +{
Remove this as well

2023-08-16 07:33 UTC, RandilaP commented
@jayasanka-sack

2023-08-16 17:56 UTC, RandilaP commented
@anjula-sack @jayasanka-sack @Piumal1999

2023-08-17 04:14 UTC, RandilaP commented
@anjula-sack @jayasanka-sack @Piumal1999

2023-08-17 12:32 UTC, RandilaP commented
@anjula-sack @jayasanka-sack @Piumal1999 Why is these report bundle and check documentations are failing

2023-08-18 12:48 UTC, RandilaP commented
@anjula-sack @Piumal1999 @jayasanka-sack

2023-08-18 17:08 UTC, RandilaP commented
@anjula-sack

2023-08-19 04:17 UTC, RandilaP commented
@anjula-sack @jayasanka-sack @Piumal1999 The documentation is failing because of a link that has 404 error. It isn't my change. What should I do

2023-08-19 04:26 UTC, anjula-sack commented on e2e/README.md
> +By default, the test suite will run against the `http://localhost:8080`.
```suggestion
By default, the test suite will run against the "http://localhost:8080".
```

2023-08-19 04:33 UTC, anjula-sack commented on e2e/README.md
> +By default, the test suite will run against the "http://localhost:8080".
```suggestion
<!-- markdown-link-check-disable-next-line -->
By default, the test suite will run against the `http://localhost:8080`.
```

2023-08-19 05:27 UTC, anjula-sack commented
@RandilaP Go to this file https://raw.githubusercontent.com/openmrs/openmrs-esm-core/main/docs/main/upgrade_3_to_4.md
 and replace the link `https://jestjs.io/docs/28.x/migration-guide` with this link `https://jestjs.io/blog/2022/04/25/jest-28`

2023-08-19 17:04 UTC, RandilaP commented
@anjula-sack @jayasanka-sack @Piumal1999

2023-08-19 17:09 UTC, anjula-sack requested changes

2023-08-19 17:09 UTC, anjula-sack commented on e2e/fixtures/index.ts
remove this empty file

2023-08-19 17:09 UTC, anjula-sack commented on e2e/commands/index.ts
This too

2023-08-19 17:17 UTC, RandilaP commented
@anjula-sack

2023-08-19 17:23 UTC, anjula-sack requested changes

2023-08-19 17:23 UTC, anjula-sack commented on e2e/specs/login.spec.ts
> +    await page.getByText("Log in").click();
This is a step. @RandilaP

2023-08-19 17:29 UTC, RandilaP commented
@anjula-sack

2023-08-19 17:36 UTC, anjula-sack requested changes

2023-08-19 17:36 UTC, anjula-sack commented on .github/workflows/e2e.yml
> +          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
This is not required @RandilaP 
```suggestion
```

2023-08-19 17:36 UTC, anjula-sack commented on .github/workflows/e2e.yml
> +          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
```suggestion
```

2023-08-20 06:24 UTC, RandilaP commented
@anjula-sack

2023-08-20 06:25 UTC, anjula-sack commented
@RandilaP Can you undo the change?

2023-08-20 06:27 UTC, RandilaP commented
@anjula-sack

2023-08-20 06:58 UTC, anjula-sack commented
@RandilaP Add cache dependency back

2023-08-20 06:58 UTC, anjula-sack commented
Replace this link as well https://zeroheight.com/23a080e38/p/880723--introduction

2023-08-20 08:18 UTC, RandilaP commented
> Replace this link as well https://zeroheight.com/23a080e38/p/880723--introduction

@anjula-sack With which link

2023-08-20 11:40 UTC, anjula-sack commented
> > Replace this link as well https://zeroheight.com/23a080e38/p/880723--introduction
> 
> @anjula-sack With which link

Just remove it @RandilaP

2023-08-20 14:31 UTC, RandilaP commented
@anjula-sack What link should I replace with that failing link

2023-08-20 14:31 UTC, anjula-sack commented
> @anjula-sack What link should I replace with that failing link

Just remove it

2023-08-20 17:34 UTC, RandilaP commented
@anjula-sack

2023-08-21 13:15 UTC, jayasanka-sack approved these changes
Thank you @RandilaP! The link check job has failed because Jira is down. Therefore, I will merge the PR.

2023-08-21 13:16 UTC, merged