(feat) Age should be represented in internationalized translated way
openmrs/openmrs-esm-core pull request #765
Opened 2023-09-11 18:49 UTC by vasharma05

## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
The age function currently returns the age in english strings, i.e. "4 years", "4 weeks". The age function will now return the age according to the locale of the application.

## Screenshots
![image](https://github.com/openmrs/openmrs-esm-core/assets/51502471/eeab8b63-3360-4a43-8897-9f10e1411d7b)

## Related Issue

## Other

2023-09-12 16:07 UTC, ibacher requested changes
We can't accept this as-is, I think. It's common to refer to ages under 2 years (and sometimes three) by months, that is "18 months" rather than "1 year 6 months", even though these refer to the same period of time. If we want to make that English-specific, I'd accept it with the endorsement of a non-English-speaking pediatrician, but absent that, we should maintain the same output as is already here.

Also, it would be best if we didn't do all of the calculations of every possible string every time, but only when they were relevant.

2023-09-27 16:32 UTC, ibacher commented on packages/framework/esm-utils/src/age-helpers.tsx
> +  const totalDaysAgoStr =
Sorry, a couple more small things:

1. Can we reduce the `getLocale()` calls to a single call?
2. It would be nice if we only calculated the strings we're actually using instead of all of them every time.
3. For weeks ago, I'd probably leave of the "days". Although this is relevant, I'm worried that the word order isn't always going to render properly, e.g., for Hebrew and Arabic, and we can fix that later.

2023-09-28 09:38 UTC, vasharma05 commented
Hi @ibacher !
I've made the changes and updated the screenshots too.

2023-10-03 18:07 UTC, ibacher approved these changes

2023-10-03 19:22 UTC, merged