(feat) O3-2484: The application should revert to default locale on logout
openmrs/openmrs-esm-core pull request #782
Opened 2023-10-06 07:26 UTC by vasharma05

## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
For an application having the default locale other than `en` (say 'km'), if the logged in user changes the locale to `en`, after the logout, the application's locale is set to `en`, instead of `km`. This PR resets the application to the default locale on logout.

## Screenshots
https://github.com/openmrs/openmrs-esm-core/assets/51502471/af84fc74-5568-44d7-97f6-98e936c97761

## Related Issue
https://issues.openmrs.org/projects/O3/issues/O3-2484

## Other

2023-10-20 01:42 UTC, brandones commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.test.tsx
> +  it("should render Logout and redirect to login page ig provider.type !== oauth2", async () => {
```suggestion
  it("should render Logout and redirect to login page if provider.type !== oauth2", async () => {
```

2023-10-20 01:49 UTC, brandones requested changes

2023-10-20 01:49 UTC, brandones commented on packages/shell/esm-app-shell/src/index.ejs
> +<html lang="<%= openmrsDefaultLocale %>" defaultLang="<%= openmrsDefaultLocale %>">
```suggestion
<html lang="<%= openmrsDefaultLocale %>" data-default-lang="<%= openmrsDefaultLocale %>">
```

Custom attributes must be prefixed.

2023-10-20 01:49 UTC, brandones commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +          document.documentElement.getAttribute("defaultLang");
```suggestion
          document.documentElement.getAttribute("data-default-lang");
```

2023-10-20 15:07 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +          document.documentElement.getAttribute("defaultLang");
Shouldn't we just be using the `lang` attribute for this?

2023-10-20 17:18 UTC, brandones commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +          document.documentElement.getAttribute("defaultLang");
The trouble is that the `lang` attribute gets updated with the user preference. That attribute is supposed to be set to the current language of that page. We need a way of storing the default language, which is passed in to the app shell and becomes an ejs parameter. I imagine there is also a way of obtaining the default without rendering it into the HTML. But I think this way of doing it is fine.

2023-10-20 17:20 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +          document.documentElement.getAttribute("defaultLang");
We have an `openmrsDefaultLocale`, although right now, that's just setting the [default value of the lang attribute](https://github.com/openmrs/openmrs-esm-core/blob/03c1200de4b1a69f58cad696e3ea39c5128a2e91/packages/shell/esm-app-shell/src/index.ejs#L2). I suppose having it also set `data-default-lang` would be a good way to go.

2023-10-20 17:21 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +          document.documentElement.getAttribute("defaultLang");
Yeah, ok, that makes sense.

2023-10-20 17:24 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.test.tsx
> +  it("should render Logout and redirect to login page ig provider.type !== oauth2", async () => {
I don't think the `if provider.type !== oauth2` is informative or useful here. If we need something here, it might be better to say `by default`.

Basically, I don't think our test descriptions should hard-code the assumption that the only `provider.types` are "default" or "oauth2".

2023-10-26 13:40 UTC, brandones commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.test.tsx
> +  it("should render Logout and redirect to login page ig provider.type !== oauth2", async () => {
@ibacher Could you take another look at this part and see if it makes sense to you? I don't know anything about provider type and oauth.

2023-10-26 13:42 UTC, brandones commented
Everything LGTM other than the `provider.type` thing @ibacher  commented on; I will let Ian take a look at the latter and give the approval.

2023-10-26 14:05 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.test.tsx
> +  it("should render Logout and redirect to login page ig provider.type !== oauth2", async () => {
I'm happy with the new test name.

How I'm thinking about this is there: there are various forms of SSO protocols (Kerberos, SAML, OIDC—which is what we're calling OAuth2) with slightly different mechanisms for communicating between the authentication server and the resource server (which is the role OpenMRS plays in any configuration). The `provider` attribute allows us to customize the way the login app works based on the expected authentication server type.

Currently, we only really have two modes: OpenMRS base authentication and OAuth2 (which is, at least OIDC-like), but it's helpful to have it be treated as more than just a binary value.

2023-10-26 14:05 UTC, ibacher approved these changes

2023-10-26 14:10 UTC, ibacher commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +        });
It might be better to make this part of the `performLogout()` or even the logic that happens [here](https://github.com/openmrs/openmrs-esm-core/blob/3fb6a3ac0ce437148f59da083ee266d34fae5e53/packages/framework/esm-api/src/shared-api-objects/current-user.ts#L183), which might solve similar issues (for instance, when a user's session times out, should the language be reset? If yes, it probably belongs in the `refetchCurrentUser()` logic), but this is only a suggestion.

2023-10-27 06:37 UTC, vasharma05 commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.component.tsx
> +        });
Right @ibacher , I'll look into that too.
Thanks!

2023-10-27 06:38 UTC, vasharma05 commented
@brandones , the changes are requested by you, can you approve the PR too?
Thanks!

2023-10-29 21:32 UTC, brandones commented on packages/apps/esm-login-app/src/redirect-logout/redirect-logout.test.tsx
> +  it("should render Logout and redirect to login page ig provider.type !== oauth2", async () => {
Nice, and thanks for the explanation!

2023-10-29 21:33 UTC, brandones approved these changes

2023-10-29 21:33 UTC, merged