[MF-180] Factor out mocks to core tooling package
openmrs/openmrs-esm-core pull request #79
Opened 2021-03-11 09:43 UTC by samuelmale

2021-03-11 10:23 UTC, FlorianRappl reviewed
Goes in the right direction, but we should work on the dev experience. The module name / path should be as simple as possible.

Also only make a mock for the framework. Don't provide mocks for anything else.

2021-03-11 10:23 UTC, FlorianRappl commented on packages/esm-devtools-app/jest.config.js
> +      "@openmrs/esm-framework/mocks/openmrs-esm-framework.mock.tsx",
Would a module name like `@openmrs/esm-framework/mock` work? Assuming that we place `mocks/openmrs-esm-framework.mock.tsx` in `mock.tsx`.

2021-03-11 10:23 UTC, FlorianRappl commented on packages/esm-framework/mocks/react-i18next.mock.js
> +const React = require("react");
Hm why is this file in there? It's not part of the framework.

2021-03-11 12:22 UTC, samuelmale commented on packages/esm-devtools-app/jest.config.js
> +      "@openmrs/esm-framework/mocks/openmrs-esm-framework.mock.tsx",
> Assuming that we place mocks/openmrs-esm-framework.mock.tsx in mock.tsx.

@FlorianRappl I don't understand what you mean here.

2021-03-11 12:24 UTC, samuelmale commented on packages/esm-devtools-app/jest.config.js
> +      "@openmrs/esm-framework/mocks/openmrs-esm-framework.mock.tsx",
You want me to rename `mocks/openmrs-esm-framework.mock.tsx` to `mocks/mock.tsx`?

2021-03-11 14:01 UTC, FlorianRappl commented on packages/esm-devtools-app/jest.config.js
> +      "@openmrs/esm-framework/mocks/openmrs-esm-framework.mock.tsx",
yes

2021-03-11 14:01 UTC, FlorianRappl commented on packages/esm-devtools-app/jest.config.js
> +      "@openmrs/esm-framework/mocks/openmrs-esm-framework.mock.tsx",
See original request

> "@openmrs/esm-framework": "@openmrs/esm-framework/mock"

2021-03-11 17:48 UTC, brandones commented on packages/esm-framework/mocks/react-i18next.mock.js
> +const React = require("react");
Yeah, but it is unfortunately necessary to mock it this way in all of the MFEs. I'd advocate including it.

2021-03-11 19:23 UTC, FlorianRappl commented on packages/esm-framework/mocks/react-i18next.mock.js
> +const React = require("react");
Why?

We have other things that qualify, too, in that area - so for consistency reasons I'd prefer to keep the framework package to framework mocks. This should not end up as a trash repository to just bring anything, but things that are esm-framework related. `react-i18next` is not.

2021-03-11 19:23 UTC, FlorianRappl requested changes
Please keep it limited to the framework mock.

2021-03-12 06:40 UTC, samuelmale commented on packages/esm-framework/mocks/react-i18next.mock.js
> +const React = require("react");
Removed react-i18next.mock.js file.

2021-03-12 09:57 UTC, FlorianRappl requested changes
Still missing:

- reportError
- interpolateString
- navigate
- getCurrentUser
- Extension
- ConfigurableLink


I got that list only by looking at some of the esm-framework.mock files in the other microfrontends.

2021-03-12 14:58 UTC, FlorianRappl approved these changes
LGTM - thanks 🍻 !

2021-03-12 14:58 UTC, merged