(feat) O3-2504: Allow saving user preference for login location as user property
openmrs/openmrs-esm-core pull request #793
Opened 2023-10-20 13:14 UTC by vasharma05

## Requirements
- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This PR allows user to save preference for login location as user property `defaultLocation`

### Workflows
1. If the user doesn't have userProperty `defaultLocation`, when the user lands on the login location page, if they check the checkbox for saving preference and save it, the selected location will be saved as the user property `defaultLocation`.
2. If the user has the user property `defaultLocation`, then when they land on the login location screen, the defaultLocation will be verified and then the user will be redirected to the home page, with session location being the same as `defaultLocation`.
3. If the user wants to update the preference, they can go to user panel on the primary navigation bar and then update the location.
3.a. If the user keeps the checkbox checked and submits, the user property `defaultLocation` will be updated.
3.b. If the user unchecks the checkbox and submits, the user property `defaultLocation` will be deleted for the user.

## Screenshots
Will add soon

## Related Issue
https://issues.openmrs.org/browse/O3-2504

## Other

2023-10-30 15:05 UTC, vasharma05 commented
>  In particular, using a userProperty assumes the user logs in before the login page, which is the current flow of the O3 RefApp, but we're seeing a number of implementations that want something more similar to the O2 page where locations are shown on the same page as logins, where using a userProperty wouldn't work.
I understand, I'll start a thread on the #openmrs3 channel.
Thanks!

2023-11-01 12:27 UTC, ibacher commented
> But for the 1st iteration, can we move ahead with this change, as this is a requirement.

Short version: The more we "move ahead" with things like this without discussion the more technical debt we accrue.

Some high-level things:

1. The name `defaultLoginLocation` is inappropriate. Semantically, we have properties already defined on the user, `defaultLocale` = user's locale when they login, if defined; `defaultLocation` = user's location when they login if defined. `preferredLoginLocation` is better.
2. Is the user the right level at which to be making this decision? Or is it better to have per-device information, e.g., something from either localStorage or a cookie or similar? (If, for example, computers are stored in physical locations, then it's very likely that clinicians using the computer want to be logged into the location the computer is located at rather than whatever their "default" clinic might be).
3. There are existing implementations of exactly this feature. For example, [module-authentication](https://github.com/openmrs/openmrs-module-authentication/blob/d7ea506bb28aaf9edb352a7e58080ba6d8542346/omod/src/main/java/org/openmrs/module/authentication/web/BasicWithLocationAuthenticationScheme.java#L88) supports this through the `sessionLocation` parameter; the O2 reference application [uses a global property to track the user attribute which stores a comma-separated list of user locations](https://github.com/openmrs/openmrs-module-referenceapplication/blob/a6dda613b882161b30df45176149e28f4ff3e665/omod/src/main/java/org/openmrs/module/referenceapplication/page/controller/LoginPageController.java#L378). So why are we inventing yet another mechanism for doing the same thing here?

2023-11-03 13:11 UTC, vasharma05 commented
Hi @ibacher @mseaton !
Based on the suggestions on [O3-2504](https://issues.openmrs.org/browse/O3-2504) and the above suggestions from @ibacher , I have created configuration points to give the implementer the freedom to choose w/e suits them better.

Please read the updated description for better understanding.
Thanks!

2023-11-08 16:15 UTC, vasharma05 commented on packages/apps/esm-login-app/src/change-location-link/change-location-link.scss
> +  // padding: 0rem 0.75rem;
Removed.

2023-11-08 16:16 UTC, vasharma05 commented on packages/apps/esm-login-app/src/config-schema.ts
> +    },
The configuration was totally removed.

2023-11-08 16:17 UTC, vasharma05 commented on packages/apps/esm-login-app/src/location-picker/location-picker.component.tsx
> +                      name="Login locations"
It's not visible on the screen, it is there in the code only.

2023-11-08 16:20 UTC, vasharma05 commented on packages/apps/esm-login-app/src/change-location-link/change-location-link.component.tsx
> +        <Button kind="ghost" onClick={changeLocation}>
Added to the PR description

2023-11-08 16:40 UTC, vasharma05 commented on packages/apps/esm-login-app/src/location-picker/location-picker.component.tsx
> +  const config: ConfigSchema = useConfig();
Done

2023-11-08 16:40 UTC, vasharma05 commented on packages/apps/esm-login-app/src/change-location-link/change-location-link.component.tsx
> +      to: `\${openmrsSpaBase}/login/location?returnToUrl=${referer}&update=true`,
Added

2023-11-08 16:41 UTC, vasharma05 commented
Hi @ibacher !
Please re-review the changes, some reviews of yours were 5 days old, which I believe wasn't added in the review back then, but was worked.

I've pushed the review changes. Thanks for your time!

2023-11-08 18:15 UTC, ibacher requested changes
Thanks @vasharma05! I think it's important to keep UI-concerns out of hooks, or at least out of hooks that are primarily about data-fetching. This leads to a cleaner and more re-usable API.

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const defaultLocation = useMemo(() => {
There's really no good reason to have `useMemo` here

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  }, [setSavePreference, defaultLocation]);
This seems like a weird concern to have in this hook... Isn't whether we're saving the preference fundamentally tied to whether the user checked the checkbox on the screen? I don't understand why the logic for this is part of this hook.

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +    async (locationUuid: string, saveUserPreference: boolean) => {
I think it's bad to call this a "preference" because it's a "default" not a "preference" per se, i.e., if this is checked, next time they login it will go to this location.

```suggestion
    async (locationUuid: string, saveDefaultLocation: boolean) => {
```

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const [searchParams] = useSearchParams();
I think having `useSearchParams()` here is a clear sign that this hook has too many responsibilities. The component can know about the search parameters, but I'm really unclear why we need this in the hook. The entirety of the `updateUserPreference()` function fundamentally is part of a component and shouldn't be done in a hook like this.

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/login.resource.ts
> +  const debouncedSearchQuery = useDebounce(searchQuery);
This also strikes me as a concern boundary that shouldn't be crossed inside this hook. The debouncing should be done in the component that uses the hook.

2023-11-08 18:15 UTC, ibacher commented on packages/apps/esm-login-app/src/login.resource.ts
> +    errorRetryCount: 0,
I don't love using this setting; this should at least be responsive to the type of error returned. A 4XX, for example, means don't retry (but you'll never get that here), a 5XX response probably should be retried...

2023-11-08 18:16 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const [searchParams] = useSearchParams();
The slightly lower-level `updateUserPropsWithPreference()` is reasonable to put in the hook because it varies with the user preferences, and that way we can minimize reloading of them.

2023-11-09 09:26 UTC, vasharma05 commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  }, [setSavePreference, defaultLocation]);
The reason I added this hook was because the `useSession` after logging in, first returns `null` and then the session object, and by that time, the initial value of the state `savePreference` is set to false, which should've been true, hence using the useEffect.

2023-11-09 09:26 UTC, vasharma05 commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const defaultLocation = useMemo(() => {
The `defaultLocation` is dependency in 2 useEffects and other useCallback functions.

2023-11-09 09:27 UTC, vasharma05 commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const [searchParams] = useSearchParams();
I understand, let me fix it.

2023-11-09 13:09 UTC, ibacher commented on packages/apps/esm-login-app/src/location-picker/location-picker.resource.ts
> +  const defaultLocation = useMemo(() => {
Right, but that's only useful if we're dealing with an object ([see the React docs](https://react.dev/reference/react/useMemo#memoizing-a-dependency-of-another-hook)). In this case, `defaultLocation` will always be: `undefined`, `null`, or some string value. Specifically, `useMemo()` helps with things like this:

```ts
let a = { a: 'Value' };
let b = { a: 'Value' };

a === b; // always false
```

But with this:

```ts
let a = 'Value';
let b = 'Value';

a === b; // always true
```

It's just overhead.

2023-11-09 14:38 UTC, vasharma05 commented on packages/apps/esm-login-app/src/login.resource.ts
> +  const debouncedSearchQuery = useDebounce(searchQuery);
The value returned by `useDebounce` is the debounced value and is consumed by the useSWR hook, hence it is in this hook.

2023-11-14 13:58 UTC, ibacher commented on packages/apps/esm-login-app/src/login.resource.ts
> +  const debouncedSearchQuery = useDebounce(searchQuery);
Right, my point is that the `useDebounce` should be in the component, not the hook. I get why it's here.

2023-11-14 17:48 UTC, ibacher approved these changes

2023-11-14 17:48 UTC, merged