(chore) ESLint: Add consistent-type-imports and no-console rules
openmrs/openmrs-esm-core pull request #837
Opened 2023-12-06 21:07 UTC by denniskigen

## Requirements
- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and **design documentation**.

#### If applicable
- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

This PR tweaks our ESLint configuration, adding rules for [consistent type imports](https://typescript-eslint.io/rules/consistent-type-imports/) as well as some other useful rules. Sorry for the huge diff.  

## Screenshots
*None*

## Related Issue
*None*

## Other
*None*

2023-12-13 18:10 UTC, ibacher requested changes
Thanks @denniskigen! Looks great. I'm not really sure what to do about my longer concern, so feel free to ignore that one.

2023-12-13 18:10 UTC, ibacher commented on .eslintrc
> +    // Use `import type` instead of `import` for type imports https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how
Personally, I'm a little iffy on this rule. Specifically, I like the idea of _requiring type qualification for type imports_, but the style I prefer is not one of the "consistent" options, specifically, the style I prefer is:

```ts
import type { Type1, Type2, Type3, Type4 } from "./types";
import {
   type Patient,
   type Visit,
   saveVisit
} from "@openmrs/esm-framework";
```

Basically, the idea is use `import type ...` if everything is a type and `import {type ...}` otherwise. This is primarily for aesthetics, i.e.,

```ts
import type { Type1, Type2, Type3, Type4 } from "./types";
```

Is (in my view) nicer than:

```ts
import {
  type Type1,
  type Type2,
  type Type3,
  type Type4,
} from "./types";
```

But also because of the transformation mentioned [here](https://typescript-eslint.io/rules/no-import-type-side-effects/) (`import {} from "./types"` might have side-effects that `tsc` cannot reason about).

2023-12-13 18:12 UTC, ibacher commented on packages/tooling/openmrs/src/utils/importmap.ts
> +      }
This does three things:

1. Makes the message source a little clearer by outputing `[openmrs] Cannot read importmap...`
2. Describes what's happening more accurately
3. Uses `console.warn()`, because by itself, a failure here does not cause the tool to fail (and this was why there was originally no message).

2023-12-14 09:50 UTC, denniskigen commented on .eslintrc
> +    // Use `import type` instead of `import` for type imports https://typescript-eslint.io/blog/consistent-type-imports-and-exports-why-and-how
Fair points, well argued. Unfortunately, it doesn't seem like the rule's configuration options gives us the desired flexibility. Glancing through the ESLint configs of popular projects, it looks like most use the [defaults](https://github.com/openmrs/openmrs-esm-core/pull/849/files). I think inlining the type import is better than separate type imports, e.g.

I find this:

```tsx
import { loadWebpackConfig, logInfo, logWarn, type ImportMapDeclaration } from '../utils';
```

Preferable to:

```tsx
import type { ImportmapDeclaration } from '../utils';
import { loadWebpackConfig, logInfo, logWarn } from '../utils';
```

Ultimately, I don't know what the preferred compromise is.

2023-12-20 19:22 UTC, ibacher approved these changes

2023-12-20 19:22 UTC, merged