O3-1409: Support for users changing passwords
openmrs/openmrs-esm-core pull request #902
Opened 2024-01-25 12:36 UTC by jnsereko

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [x] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

 O3 screen to allow users to change their password.
cc @michaelbontyes @vasharma05 @denniskigen @hadijahkyampeire 

## Screenshots

https://github.com/openmrs/openmrs-esm-core/assets/58003327/1c41012c-97a6-4d5e-b0d7-d31a8cbb00af

## Related Issue

https://openmrs.atlassian.net/browse/O3-1409

## Other

2024-01-31 17:35 UTC, ibacher requested changes
@jnsereko This is great work in many ways! A few things:

1. I think it would be preferable to have this as part of the (much neglected) openmrs-esm-admin-tools repo.
2. Instead of a full page, I think the password change could be handled as a modal.
3. As a modal, I think the width could be much smaller than it presently is.

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password-button/change-password-button.component.tsx
> +      <SwitcherDivider className={styles.divider} />
I don't think that the `SwitcherDivider` should be part of this class.

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password-button/change-password-button.component.tsx
> +export default ChangePasswordLink;
```suggestion
export default ChangePasswordLink;

```

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password-button/change-password-button.scss
> +  width: 16rem;
Using the Carbon `$spacing` utils. I'm also not sure why you're importing `../root.scss` here?

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password/change-password.component.tsx
> +        errMsg = 'Password is empty';
Any display string always needs to be translatable.

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password/change-password.component.tsx
> +                    style={{ maxWidth: '50%' }}
I'd use SCSS rather than inline styles for this.

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password/change-password.resource.ts
> +  const abortController = new AbortController();
Not much use for an AbortController inside this method. This is what `useAbortController()` is for (automatically aborts requests when the UI unmounts a component).

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password/change-password.component.tsx
> +        if (response.ok) {
`if (repsonse.ok)` is redundant. `openmrsFetch` throws an exception (so the Promise will throw an error) if the result isn't ok.

2024-01-31 17:35 UTC, ibacher commented on packages/apps/esm-login-app/src/change-password/change-password.component.tsx
> +            const defaultLang = document.documentElement.getAttribute('data-default-lang');
Uh... just redirect to the logout handler I guess... We've never forced people to re-login after changing their password though, so I'm not a huge fan of this.

2024-02-01 14:57 UTC, jnsereko commented
thank you @ibacher for taking a look at this.  
i have moved this logic to esm-admin-tools repo and added it to the `@openmrs/esm-system-admin-app'  hence i am closing this PR 
 follow up PR -> https://github.com/openmrs/openmrs-esm-admin-tools/pull/43

2024-02-01 14:58 UTC, closed without merging