O3-2691: Added E2E logout test
openmrs/openmrs-esm-core pull request #904
Opened 2024-01-26 09:23 UTC by kdaud

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

 https://issues.openmrs.org/browse/O3-2691

## Other

2024-02-01 19:29 UTC, ibacher commented on e2e/specs/login.spec.ts
> -  await test.step('And I should be able to see various elements on the page', async () => {
Why did you remove this step? Also, I'm not really sure about the rewording of the steps; the language here was fine.

2024-02-01 19:29 UTC, ibacher commented on e2e/specs/login.spec.ts
> +  await test.step('And click on `Logout` button', async () => {
This should be an entirely different test. Logging out is not part of the `Login` feature (although it's part of the same app).

2024-02-01 23:33 UTC, denniskigen commented on e2e/specs/login.spec.ts
> -  await test.step('And I should be able to see various elements on the page', async () => {
@kdaud [this](https://talk.openmrs.org/t/seeking-feedback-on-proposed-e2e-testing-improvements-with-bdd-like-syntax-and-playwright-test-step/39596/9) is the rationale behind why our E2E tests are worded as they are.

2024-02-02 12:45 UTC, kdaud commented
@denniskigen @ibacher  @jayasanka-sack there is [this](https://github.com/kdaud/core-esm/actions/runs/7755710471/job/21151631323#step:7:159) error from the OpenMRS CI job which is failing the build. I guess it's not linked to the changes as I'm registering it also on the main branch. Could you be knowing the root cause of the error? Thanks.

2024-02-05 07:59 UTC, kdaud commented
@ibacher @denniskigen the issue got fixed, the PR is ready for review.

2024-02-05 17:26 UTC, Piumal1999 commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
Instead of including the login process in this step, can we use a global-setup which has signed-in state [similar to what we have in other mono repos](https://github.com/openmrs/openmrs-esm-patient-management/blob/main/e2e/core/global-setup.ts)? 
(**Only if there's a way to exclude the login e2e test from using the signed-in state.**)

What do you think @jayasanka-sack ?

2024-02-05 17:26 UTC, Piumal1999 commented on e2e/specs/logout.spec.ts
> +    await expect(page.getByText('Cannot read properties of undefined (reading `person`)')).not.toBeVisible();
I think it's better to check for a generic error notification without specifying a particular error message. Because, we need to ensure that the test fails if there are different errors.

So, I believe the best approach should be checking whether there are no visible error notifications, like this:

<img width="649" alt="image" src="https://github.com/openmrs/openmrs-esm-core/assets/27498587/886e0e6c-b9b1-45da-8082-84248fd9593f">

2024-02-06 00:43 UTC, brandones commented on e2e/specs/logout.spec.ts
> +    await expect(page.getByText('Cannot read properties of undefined (reading `person`)')).not.toBeVisible();
You can probably just look for the word "error" (case insensitive). If any text appears on the screen with the word "error," there's trouble.

2024-02-06 11:16 UTC, kdaud commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
@jayasanka-sack what is your take on this?

2024-02-06 11:27 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
Yes @Piumal1999 , that's a nice idea and will be helpful for future tests. 

We use a feature named [storageState](https://github.com/microsoft/playwright/issues/11809#issuecomment-1146575789) in playwright, and we can skip it for a specific test. https://github.com/microsoft/playwright/issues/11809#issuecomment-1146575789

2024-02-06 21:05 UTC, brandones commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
If that's not nearly-trivial, I would suggest doing it in a separate PR so we can merge this quickly.

2024-02-07 06:47 UTC, kdaud commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
I'll add a separate PR to set the global-setup for E2E tests and skip the login test.

2024-02-07 07:29 UTC, kdaud commented on e2e/specs/logout.spec.ts
> +    await loginPage.enterLoginCredentials();
Created a ticket at https://openmrs.atlassian.net/browse/O3-2823

2024-02-07 07:42 UTC, jayasanka-sack requested changes
Requested some minor changes related to steps.

2024-02-07 07:42 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +    await expect(page.getByRole('button', { name: /logout/i })).toBeVisible();
These lines are incongruent with the provided step. Typically, "expects" statements are aligned with "Then" steps, unless necessitating action.

2024-02-07 07:42 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +  });
Let's break this into two steps.
- Then I should be redirected to the login page
- And I should not see any error messages

2024-02-07 07:42 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +  });
This step doesn't actually describe what actions are performed. 

Maybe break down it to:
- When I go to Login page
- And I enter my login credentials
- Then I should be in the home page

Also,
`page.goto('home');` is redundant as it automatically redirects to the home page after the login.

2024-02-08 05:56 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +  await test.step('And I click the `User` button', async () => {
```suggestion
  await test.step('When I click the `User` button', async () => {
```

2024-02-08 05:56 UTC, jayasanka-sack commented on e2e/specs/logout.spec.ts
> +    await expect(page.getByText(/super user/i)).toBeVisible();
Do we nee this?

2024-02-08 06:16 UTC, kdaud commented on e2e/specs/logout.spec.ts
> +    await expect(page.getByText(/super user/i)).toBeVisible();
Well, not necessarily.

2024-02-08 06:34 UTC, jayasanka-sack approved these changes
Thanks a mill, Daud! ❤️

What would be the next steps from here?
Could you please take a look at [O3-2823](https://openmrs.atlassian.net/browse/O3-2823) and work on it as needed?

2024-02-08 06:34 UTC, merged