O3-2732 Added logic to allow dynamic adjustment of Logo in NavBar
openmrs/openmrs-esm-core pull request #907
Opened 2024-01-28 18:47 UTC by suubi-joshua

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

## Other

2024-01-30 11:06 UTC, Vijaykv5 commented
Have a question @suubi-joshua 
If width keep you keep max `300`, will it get congested by height? 
or will it effect logo congestion?

2024-01-30 13:16 UTC, suubi-joshua commented
> Have a question @suubi-joshua
> If width keep you keep max `300`, will it get congested by height?
> or will it effect logo congestion?

thanks for feedback @Vijaykv5 
The max width is 300 but default is 110.
The changes are incase anyone wants to change the width they cannot go beyond 300. On the aspect of congestion (https://openmrs.atlassian.net/browse/O3-2732). I think the person who reported this issue could give a reason why 300 @ibacher

2024-01-30 16:14 UTC, ibacher commented
300px is an arbitrary number, basically triple the current size. The height, however, of the logo is fixed, so we're basically just accommodating extra text.

@suubi-joshua I think the width has to come from configuration, not a property. The idea is that the OpenMRS logo is a fixed size (110x40), but if someone is using a custom logo, they may want / need it to be a custom size. We will not know that in the code that mounts the logo though.

2024-01-31 20:13 UTC, suubi-joshua commented
> 300px is an arbitrary number, basically triple the current size. The height, however, of the logo is fixed, so we're basically just accommodating extra text.
> 
> @suubi-joshua I think the width has to come from configuration, not a property. The idea is that the OpenMRS logo is a fixed size (110x40), but if someone is using a custom logo, they may want / need it to be a custom size. We will not know that in the code that mounts the logo though.

@ibacher Made some changes.

2024-02-01 12:39 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
Currently there's no config for the logo width, you have to add it here: https://github.com/openmrs/openmrs-esm-core/blob/main/packages/apps/esm-login-app/src/config-schema.ts

2024-02-01 12:45 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
However, the idea of the ticket is just to introduce a max width for the logo and let it scale, isn't it @ibacher ?

2024-02-01 13:16 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
> Currently there's no config for the logo width, if you need a config, you have to add it here: https://github.com/openmrs/openmrs-esm-core/blob/main/packages/apps/esm-login-app/src/config-schema.ts

I have put it in the config schema

2024-02-02 14:18 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
I think this can be easily solve by just introducing max-width for the logo without introducing any config.

Also do not hard code the width, let the logo to scale. providing a width eventually lead the logo to stretch, which might look wonky if the provided width isn't quite right.

2024-02-02 15:18 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
@jayasanka-sack I believe this is a better option. cc @ibacher

2024-02-02 16:01 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
@suubi-joshua My point is, why should someone explicitly provide the width, where it can just be calculated? 

Since the height is fixed, the logo can be **scaled** based on it's dimensions. i.e. the width should auto adjusted (up to 300px based on the ticket)

2024-02-02 16:12 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
>          </svg>
Keep this as it is, as it serves as the fallback logo with known dimensions.

2024-02-03 18:11 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
@jayasanka-sack Thanks let me work on this.

2024-02-05 01:35 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +  const logoWidth = logo?.width || 110;
> @suubi-joshua My point is, why should someone explicitly provide the width, when it can be calculated?
> 
> Since the height is fixed, the logo can be **scaled** based on it's dimensions. i.e. the width should auto adjusted (up to 300px, according to the ticket)

@jayasanka-sack made some changes to address this.

2024-02-06 13:49 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
>          </svg>
Do not do any changes for this line.

https://github.com/openmrs/openmrs-esm-core/pull/907#discussion_r1476259061

2024-02-06 13:51 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +
I think this could achieve by only using CSS. Do necessary changes to the `styles.logo` class.

2024-02-08 06:49 UTC, jayasanka-sack requested changes

2024-02-08 06:49 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.scss
> +  width: 110;
Don't provide the width. let it scale.

2024-02-08 06:49 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +
No need of this.

2024-02-08 07:06 UTC, jayasanka-sack commented
It appears to me that you don't have a clear idea about the ticket and its overall objective. Could you please provide your understanding of the issue outlined in the ticket? This will help ensure we're on the same page and allow me to address any misunderstandings.

2024-02-08 07:10 UTC, jayasanka-sack commented
@Vijaykv5, could you lend a hand to @suubi-joshua?

2024-02-08 08:53 UTC, suubi-joshua commented
> It appears to me that you don't have a clear idea about the ticket and its overall objective. Could you please provide your understanding of the issue outlined in the ticket? This will help ensure we're on the same page and allow me to address any misunderstandings.

@jayasanka-sack @Vijaykv5 this is what am trying to solve or how I am understanding the issue. The goal is to make the width of the logos more flexible so that they can scale between a minimum width of 110 pixels and a maximum width of 300 pixels. This allows for accommodating logos of varying widths, especially those with longer text or larger graphics, while still maintaining a consistent height of 40 pixels. This change should ensure that the navigation bar can accommodate a wider range of logo sizes without distorting the layout or appearance of the app.

2024-02-08 08:54 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.scss
> +  width: 110;
@jayasanka-sack okay it should not have a fall back value of width ?

2024-02-08 11:40 UTC, suubi-joshua commented
@Vijaykv5 and @jayasanka-sack from the most recent changes this is what happens when i input some random logos in configs
[Logo adjustment test.webm](https://github.com/openmrs/openmrs-esm-core/assets/78343336/2e214962-85b1-4f1a-adaf-13156143c14c)

2024-02-08 12:26 UTC, suubi-joshua commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +
I have removed this as well but kept the constant of logoWidth. I set it to the default width of the omrs logo width.

2024-02-15 16:26 UTC, jayasanka-sack commented
Awesome!

Test with logos with following ratios and share screenshots instead a video: (`w:h`)
1.  `<15 x 2` (ex `100px x 100px`)
2.  `15 x 2` 
3. `15> x 2` (The image should be cropped at this ratio; i.e. whatever goes beyond 300px should be cropped)

The height should be 40px all the time.

2024-02-15 16:31 UTC, jayasanka-sack commented
@suubi-joshua 
> ....this is what am trying to solve or how I am understanding the issue. The goal is to make the width of the logos more flexible so that they can scale between a ~minimum width of 110 pixels~ and a **maximum width of 300 pixels**. This allows for accommodating logos of varying widths, especially those with longer text or larger graphics, while still maintaining a **consistent height of 40 pixels**. This change should ...

Also, what goes beyond 300px should be cropped

2024-02-15 16:33 UTC, jayasanka-sack commented on packages/apps/esm-primary-navigation-app/src/components/logo/logo.component.tsx
> +    const logoWidth = 110; //default width for the omrs logo
No need for this.

2024-02-15 21:20 UTC, suubi-joshua commented
@jayasanka-sack these are the logos I have tested with the ratios you gave. Not that clear logo pictures. Do you have any logo suggestions.
![Screenshot from 2024-02-15 23-25-37](https://github.com/openmrs/openmrs-esm-core/assets/78343336/faf82199-4c84-4043-b938-2a5216264f2b)
![Screenshot from 2024-02-15 23-28-25](https://github.com/openmrs/openmrs-esm-core/assets/78343336/af048ca5-3133-4479-b6c9-ac2f16c35f85)
![Screenshot from 2024-02-15 23-42-25](https://github.com/openmrs/openmrs-esm-core/assets/78343336/3b5cb2b1-7110-41dc-9fe7-d1ffb5d9ca31)
![Screenshot from 2024-02-15 23-52-53](https://github.com/openmrs/openmrs-esm-core/assets/78343336/ee6e6aad-73dc-4e03-92df-004a0e44bd14)
![Screenshot from 2024-02-16 00-12-32](https://github.com/openmrs/openmrs-esm-core/assets/78343336/3db51735-e472-499b-a038-73fb3d148340)

2024-02-16 07:35 UTC, jayasanka-sack commented
can you try this one: (`580 x 40`; `29:2`)
<img width="584" alt="image" src="https://github.com/openmrs/openmrs-esm-core/assets/33048395/b82aa40b-4410-4684-b160-effccd82854b">

2024-02-18 20:57 UTC, suubi-joshua commented
@jayasanka-sack how is this. Though this was produced after some changes. In the css file without putting px at the end of 300 didnt produce any adjustment. So i had to do that small change. Though am still failing to push because of this failing test https://pastebin.com/HSNaPS4J
![Screenshot from 2024-02-18 23-50-02](https://github.com/openmrs/openmrs-esm-core/assets/78343336/60a18f54-4ef8-4e3b-ab41-08025dcfac1f)

2024-02-20 17:46 UTC, ibacher approved these changes

2024-02-20 17:46 UTC, ibacher commented
Approved with minor changes requested.

2024-02-21 09:17 UTC, jayasanka-sack commented
@ibacher the logo has to be cropped if the width is greater than 300px, right?

2024-02-21 14:55 UTC, ibacher commented
Ideally. Re-looking at the screenshot above, it looks like the image is being re-scaled, which is not the behaviour we want.

2024-02-21 15:54 UTC, suubi-joshua commented
![TestImage(1)](https://github.com/openmrs/openmrs-esm-core/assets/78343336/15647a34-c219-49d6-ad7d-cab877549a72)

2024-02-22 12:55 UTC, suubi-joshua commented
![image](https://github.com/openmrs/openmrs-esm-core/assets/78343336/f12c465f-6b80-4807-bdcf-de98b729cfe6)
@jayasanka-sack kindly elaborate on the cropping you mean, I am confused on that I have comeup with this a few tweaks.

2024-02-22 13:32 UTC, suubi-joshua commented
@jayasanka-sack Also not sure why check documentation test is failing.

2024-03-07 12:11 UTC, denniskigen commented
A link to the wiki was taking a while to load https://openmrs.atlassian.net/wiki/spaces/projects/pages/26936899/OpenMRS+3.0+A+Frontend+Framework+that+enables+collaboration+and+better+User+Experience. I've rerun the task.

2024-04-17 11:18 UTC, ibacher approved these changes

2024-04-17 11:19 UTC, merged