(feat) O3-2790: Create a reusable location picker component
openmrs/openmrs-esm-core pull request #913
Opened 2024-02-01 07:46 UTC by jayasanka-sack

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

## Other

2024-02-01 08:33 UTC, jayasanka-sack commented
@ibacher The e2e test is failing for this PR as we don't package esm-framework. What can we do?

 https://github.com/openmrs/openmrs-esm-core/blob/main/e2e/support/github/run-e2e-docker-env.sh

2024-02-01 14:06 UTC, ibacher commented
Several things:

* What connections does this PR (move the location picker to the styleguide) have with the ticket (additional locations not loading in Chrome-based browsers)?
* I don't think data-fetching components, in general, belong in the styleguide without a strong justification. I'm having trouble seeing where else this component is useful.
* In general, we do not want to end up with a large component library because that becomes a maintenance headache.

2024-02-01 14:07 UTC, ibacher requested changes
See previous comment as well.

2024-02-01 14:07 UTC, ibacher commented on packages/framework/esm-styleguide/src/location-picker/location-picker.module.scss
I don't think `.module.scss` is consistent with our naming conventions (and the couple of other places it's used should be fixed).

2024-02-02 14:46 UTC, ibacher commented
@jayasanka-sack So, I'm on-board with a component for viewing locations. I'm less keen on the _data-fetching_ part living in the styleguide. That is, I think the fetching should be handled by a component that mounts this component and passed in as props rather than having the fetch logic itself in the styleguide. There might be a case for putting those hooks in esm-react-utils...

There are issues with components in the styleguide, like the translation system won't work nor will the configuration system. Components in the styleguide should really just be, effectively the HTML markup and component behaviour (like drop-downs or something).

2024-02-02 14:48 UTC, ibacher commented
And, yeah, for the e2e tests in core, we also need to run the `build` step.

2024-03-23 04:09 UTC, brandones commented on packages/framework/esm-styleguide/src/location-picker/location-picker.module.scss
Yeah @ibacher unfortunately it's a webpack issue, `.module.scss` magically makes the styles work. I don't understand it. @denniskigen pointed it out to me.

2024-03-23 04:23 UTC, brandones commented
Yeah let's please file a ticket specifically about this, under https://openmrs.atlassian.net/browse/O3-1422. Do O3-2790 separately.

Please also document the places in the code that this location picker would be used. What existing location pickers exist throughout O3? It's important to make sure that styleguide components are very well designed in terms of being adequate for current use cases (while being minimalist in their API and simple in their implementation).

I don't have strong feelings about whether the data fetching is included or not. I'm inclined to say that whether it should be included should depend on whether users of the component will want control over the data that gets used. For example, the Patient Banner Contact Details component fetches the patient object; this is fine because it would be very strange for someone to want to customize the patient data being used. But here, there is already the location tag prop, which indicates some need for customization. On the other hand, Infinite Scroll requires a pretty high degree of coupling between the UI and data fetcher. So it might be hard to design a good component API where the data is provided by the component user.

2024-03-23 04:25 UTC, brandones commented
We do have `esm-styleguide` configuration—importantly, if the location picker uses that, it will be the same across the app.

And we now support core translations, as you all know :)

2024-06-04 21:00 UTC, brandones commented
GitHub seems to have a bug. There is no conflict, and I cannot figure out how to tell it that. I have never had to do this before, but I think we actually have to close and re-open this PR. Sorry about that @jayasanka-sack and @ibacher .

2024-06-04 21:29 UTC, brandones commented
@jayasanka-sack I have merged this with the latest. Please give it a look over to see if you think I messed anything up. It was an extremely messy merge.

2024-06-05 15:36 UTC, jayasanka-sack commented
Thanks @brandones ! Let me try to fix this.

2024-07-03 21:08 UTC, brandones commented
@jayasanka-sack Ping, any news or blockers to report?

2024-07-05 14:56 UTC, jayasanka-sack commented
@brandones I tried to fix this earlier, but this seemed to take time to fix, so I had to deprioritize it in favor of the load testing work. I'll try working on it again.

2024-07-09 13:37 UTC, jayasanka-sack commented
@brandones I fixed the issue: it was with this line: https://github.com/openmrs/openmrs-esm-core/blob/57f86e981f2907d5a1c31acaa6449998a6cb656d/packages/apps/esm-login-app/src/location-picker/location-picker.test.tsx#L47

2024-07-09 15:11 UTC, brandones commented
@jayasanka-sack Nice! Is this the same issue?

```
@openmrs/esm-primary-navigation-app:test
cache miss, executing 5f88d48b99dbf1e6
 PASS  src/components/logo/logo.test.tsx (10.834 s)
 FAIL  src/root.component.test.tsx
  ● Test suite failed to run

    ReferenceError: Cannot access 'importDynamic' before initialization

      14 | export * from '@openmrs/esm-state/mock';
      15 | export * from '@openmrs/esm-styleguide/mock';
    > 16 | export * from '@openmrs/esm-translations/mock';
         |         ^
      17 |
      18 | /* esm-globals */
      19 |
```

Thanks for your continued work on this!

2024-07-09 15:41 UTC, jayasanka-sack commented
> @jayasanka-sack Nice! Is this the same issue?

Yes. fixed with: https://github.com/openmrs/openmrs-esm-core/pull/913/commits/17bb8c4f31be07864a229d9a90442d8a30901994

2024-07-09 19:35 UTC, brandones commented
Whoops, same problem, other tests...

2024-07-11 15:48 UTC, jayasanka-sack commented
@brandones We had a call yesterday on the O3 leads call, and we thought of first finding out why they are failing only on this PR before fixing the anti-pattern usage for mocks. @ibacher were you able to find any clue?

2024-07-15 15:10 UTC, jayasanka-sack commented
@ibacher, were you able to find the root cause by any chance?

2024-07-31 12:59 UTC, ibacher approved these changes

2024-07-31 13:32 UTC, merged

2024-07-31 13:33 UTC, brandones commented
:tada: :tada: :tada: Thank you @jayasanka-sack and @ibacher on getting this through!!!

2024-07-31 14:21 UTC, jayasanka-sack commented
Thanks a ton @brandones @ibacher! This is such a big relief!!

2024-07-31 14:35 UTC, jayasanka-sack commented
It was failing for the same reason since it takes a bit of time to get the esm framework published to the registry, and the e2e job uses whatever the latest version. It's passing now!

2024-07-31 16:10 UTC, ibacher commented
@jayasanka-sack The ultimate issue, AFAICT, with E2E tests and framework changes is that on the Docker image, we rely on the latest published version of the app-shell (basically [this stuff](https://github.com/openmrs/openmrs-esm-core/blob/08fe1eab4e7a67fedca9947e1d15f50df48cde2d/e2e/support/github/Dockerfile#L11)). The problem is that version of the app-shell will be linked to the old version of the framework and so stuff fails.

2024-07-31 16:33 UTC, jayasanka-sack commented
Thanks @ibacher! Isn't it because we build the container on top of the `openmrs-reference-application-3-frontend:nightly` image that already has the framework on it, and it takes some time to build the image in Bamboo and publish it to docker hub?

https://github.com/openmrs/openmrs-esm-core/blob/08fe1eab4e7a67fedca9947e1d15f50df48cde2d/e2e/support/github/Dockerfile#L15

2024-07-31 16:36 UTC, ibacher commented
Yeah, that's also a factor there...

2024-07-31 17:26 UTC, jayasanka-sack commented
> for a PR, though, the image will never be updated until the PR is merged.


I agree. 

I was referring to this : https://github.com/openmrs/openmrs-esm-core/actions/runs/10181254724/attempts/1