(feat) O3-2808: Add auto dismissing on snackbars
openmrs/openmrs-esm-core pull request #916
Opened 2024-02-05 13:07 UTC by usamaidrsk

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

[O3-2808](https://openmrs.atlassian.net/browse/O3-2808)

## Other

2024-02-06 06:54 UTC, vasharma05 commented
Hi @usamaidrsk!
Please add a screenshot.
Thanks!

2024-02-06 11:32 UTC, usamaidrsk commented
@vasharma05 , @denniskigen  I have added a video to demo the changes
Thanks

2024-02-06 13:57 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +import React, { useState, useEffect, useCallback, useMemo } from 'react';
`useMemo` isn't used anywhere here, right?

2024-02-06 13:58 UTC, jayasanka-sack commented
Thanks for the PR, Usama! Could you please add a unit test for this?

2024-02-06 14:00 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    if (timeoutInMs || canAutoClear) {
Why do we check for `timeoutInMs` here?

2024-02-06 19:49 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    if (timeoutInMs || canAutoClear) {
`timeoutInMs` value at some point it won't be passed on calling `showSnackbar`, thus it's checked and if it has a value, then the `snackbar` will clear after the time defined,  else clear after 5s if the `snackbar` has auto clear

Thanks @jayasanka-sack

2024-02-06 20:56 UTC, ibacher requested changes

2024-02-06 20:56 UTC, ibacher commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    const canAutoClear = kind === 'success' || (!userDismissible && (kind === 'warning' || kind === 'warning-alt'));
The rule here should basically be `kind !== 'error'`. This leaves out `info`.

2024-02-06 20:56 UTC, ibacher commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    userDismissible,
I don't really get why we need a `userDismissable` property here?

2024-02-06 20:56 UTC, ibacher commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    const canAutoClear = kind === 'success' || (!userDismissible && (kind === 'warning' || kind === 'warning-alt'));
TBH, I'm not even 100% on this. I think an acceptable solution to this would be:

```
const {
 // ... snip
 timeoutInMs = 5000,
 // ... snip
} = snackbar;
```

2024-02-07 03:34 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    userDismissible,
I added `userDismissable` so as to bringout what the description mentioned about warning snackbars on the ticket you filed @ibacher 
That when on creating a warning snackbar it can be created with `userDismissable` true, so as not to auto clear.

"Snackbar notifications for warnings should default to clearing with the option to make them remain until cleared."

2024-02-07 03:37 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    const canAutoClear = kind === 'success' || (!userDismissible && (kind === 'warning' || kind === 'warning-alt'));
I think I can change to have that, and test it out

2024-02-07 07:55 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    if (timeoutInMs || canAutoClear) {
Given that there's a default timeout set for 5 seconds, it's necessary to close it regardless of whether the `timeoutInMs` parameter has a value or not, correct?

2024-02-07 08:07 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    userDismissible,
in that case, how about having a prop names something like `autoClose`?

the behaviour would be,
- if `autoClose` value is provided:  
    autoClose based on the provided value regardless the notification kind.
- if not provided,
    the `autoClose`s default value should be (feel free to use default value or suitable approach)
    - `true` for `success`
    - `false` for warnings and errors

2024-02-07 09:08 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    userDismissible,
Okay, thanks @jayasanka-sack

2024-02-07 09:38 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    userDismissible,
cc @jayasanka-sack I have pushed some updates
Thanks

2024-02-09 20:10 UTC, denniskigen commented
@ibacher could you re-review?

2024-02-09 20:25 UTC, ibacher reviewed
Aside from one small nit, LGTM. Thanks @usamaidrsk!

2024-02-09 20:25 UTC, ibacher commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const closeSnackbar = () => {
General rule: any function created inside a functional component and passed to a child should use `useCallback()`. This is because the function body gets run on each render cycle, so each time, `closeSnackbar` is a new function, which means that the child component will re-render every time this component re-renders even if none of it's other props have changed.

2024-02-10 13:58 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const closeSnackbar = () => {
Thanks for the notes @ibacher

2024-02-10 21:43 UTC, denniskigen approved these changes

2024-02-12 17:36 UTC, denniskigen commented
Good to go, @ibacher?

2024-02-12 17:49 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const [actionText, setActionText] = useState(actionButtonLabel || '');
Why do we need a state?

2024-02-12 17:52 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const [actionText, setActionText] = useState(actionButtonLabel || '');
Any specific reason for this?

We can use it directly, right? 
```
 <ActionableNotification
      actionButtonLabel={actionButtonLabel}
```

2024-02-12 17:59 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    setTimeout(removeSnackBarFromDom, 250);
Where the implementation for `removeSnackBarFromDom` comes from? Do we need to pass it as a prop?

2024-02-12 18:00 UTC, jayasanka-sack requested changes
Usama, can you please write a unit test for this?

2024-02-12 18:04 UTC, ibacher commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    setTimeout(removeSnackBarFromDom, 250);
It's the second prop already...

2024-02-12 18:07 UTC, ibacher approved these changes

2024-02-12 18:57 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    setTimeout(removeSnackBarFromDom, 250);
yes, but do we need to pass how to remove it on everywhere we use the snackbar? Can't we implement it within the component?

2024-02-12 19:01 UTC, jayasanka-sack commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    setTimeout(removeSnackBarFromDom, 250);
Oh. I read the implementation. Makes sense now.

2024-02-13 05:01 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const [actionText, setActionText] = useState(actionButtonLabel || '');
I agree, I don't know why this was resolved.

`setActionText` is not being used, then why are we using a state?

2024-02-13 07:07 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const [actionText, setActionText] = useState(actionButtonLabel || '');
```typescript
const handleActionClick = () => {
    onActionButtonClick();
    onCloseSnackbar();
    progressActionLabel && setActionText(progressActionLabel);
  };
``` 

@vasharma05 it is used here, Thanks

2024-02-13 07:31 UTC, vasharma05 commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +  const [actionText, setActionText] = useState(actionButtonLabel || '');
Hi @hadijahkyampeire!
Any reason why we use progressActionLabel since it is being set after the snack bar is closed?
Can we remove it all?
Thanks!

2024-02-13 12:07 UTC, vasharma05 commented
@jayasanka-sack, please re-review the PR.
Thanks!

2024-02-13 17:52 UTC, denniskigen commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    autoClose = kind !== 'error',
Ultimately, we'll likely want to revisit this logic. Consider actionable success notifications for example. Do we want them to stick around until the user dismisses the snackbar manually? If so, this logic won't work. Good enough to go for now imo, but worth thinking about nonetheless.

2024-02-13 19:23 UTC, usamaidrsk commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    autoClose = kind !== 'error',
Nice catch. I think we can still add that check too.
Given that what makes a snackbar actionable, is when `actionButtonLabel` and `onActionButtonClick` are provided, if I am right.

cc @denniskigen

2024-02-13 19:51 UTC, denniskigen commented on packages/framework/esm-styleguide/src/snackbars/snackbar.component.tsx
> +    autoClose = kind !== 'error',
Yeah, it'll require some tweaking, and would probably be best done in a separate follow-up PR rather than trying to anticipate all the possible situations here.

2024-02-14 12:57 UTC, jayasanka-sack approved these changes

2024-02-14 15:12 UTC, merged

2024-02-14 15:12 UTC, ibacher commented
Thanks @usamaidrsk and everyone!