DRAFT: Move patient banner info section into styleguide
openmrs/openmrs-esm-core pull request #919
Opened 2024-02-08 04:39 UTC by brandones

Getting feedback. See https://github.com/openmrs/openmrs-esm-patient-chart/pull/1645

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

## Other

2024-02-08 04:41 UTC, brandones commented on packages/framework/esm-styleguide/src/config-schema.ts
> +    _description:
Unrelated, this was lacking a description and validation.

2024-02-08 20:08 UTC, ibacher reviewed
In principle, I like the approach and this is a very reasonable component to move into the styleguide.

2024-02-08 20:08 UTC, ibacher commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  // TODO: We ought to have some kind of "core translations."
Yes!

2024-02-08 20:08 UTC, ibacher commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +          just provide `isDeceased` as state. */}
I think, in principle, we want the `patient-banner-tags-slot` to be able to load implementation-defined tags. It's true that we only actively use this for `isDeceased`, but an implementation-specific tag may have additional uses for the patient record.

2024-02-08 20:08 UTC, ibacher commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  const { excludePatientIdentifierCodeTypes } = useConfig();
What configuration is this going to pick up? This might be better passed in a prop to this component?

2024-02-08 20:30 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +          just provide `isDeceased` as state. */}
Yeah, the trouble is that the patient banner doesn't always have access to the `fhir.Patient`. Specifically in the patient-search component, what is available is a SearchedPatient object, so the state passed to the tags slot ends up being this [terrible hack](https://github.com/openmrs/openmrs-esm-patient-management/blob/90ca8beba97580524d5ccfed10eb885e834589f1/packages/esm-patient-search-app/src/patient-search-page/patient-banner/banner/patient-banner.component.tsx#L84-L88). It would be better if the API could be satisfied by all the slots.

2024-02-08 20:31 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  const { excludePatientIdentifierCodeTypes } = useConfig();
This will be the styleguide config, which already exists. We'd want to pass it as props if we want it to be possible to configure differently in different apps, and I'm not sure why we'd want that.

2024-02-08 20:32 UTC, ibacher commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +          just provide `isDeceased` as state. */}
Ah... that's awful. I had some designs on re-working the search to use the FHIR API, now that there's actually an endpoint that's responsive to our actual needs, but we haven't made the switch yet.

2024-02-08 20:44 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  // TODO: We ought to have some kind of "core translations."
My idea is to define a new core app just called like `@openmrs/esm-core-translations` that just serves translations, and then add a new function to the framework (maybe `esm-utils`, unfortunately) that basically just does

```ts
function getCoreTranslation(key, default) {
  return translateFrom('@openmrs/esm-core-translations', key, default)
}
```

We could even maintain a tuple type for `key` so clients know via typescript exactly what translation keys are available in core.

2024-02-08 20:45 UTC, brandones commented
> In principle, I like the approach and this is a very reasonable component to move into the styleguide.

Should I do these components one at a time, or expand this PR to do all four patient banner components?

2024-02-08 20:45 UTC, ibacher commented
> Should I do these components one at a time, or expand this PR to do all four patient banner components?

I'm happy to just have one PR that does everything.

2024-02-08 20:48 UTC, ibacher commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  const { excludePatientIdentifierCodeTypes } = useConfig();
`useConfig()` by default uses the `ComponentContext` to figure out which module to use the config for, so in the current chart PR, it works because it's still resolving to "@openmrs/esm-patient-banner-app". I guess I'm really asking: should we have some kind of pattern for modifying the `ComponentContext` for components from the styleguide or use `useConfig({ externalModuleName: "@openmrs/esm-styleguide" })` (this syntax is intentionally clunky to avoid people over-relying on it).

2024-02-17 23:57 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  const { excludePatientIdentifierCodeTypes } = useConfig();
Oh that's right! Good thinking. I'm fine with either, I suppose, as long as it's an implementation detail handled by esm-styleguide code so that app developers don't have to think about it. I am inclined to use `externalModuleName` just because it seems simpler to me (and I'm not averse to using core's more questionable features within core itself).

2024-02-18 00:10 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +          just provide `isDeceased` as state. */}
Oh! If we do that then the interface to `PatientBannerPatientInfo` could also be simplified just to accept the patient object. I'm actually inclined to wait on this until we change patient search to use the fhir patient. It looks like all other usages of the patient banner use the fhir patient.

2024-02-18 00:11 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +          just provide `isDeceased` as state. */}
Is there a ticket for that?

2024-02-18 00:46 UTC, brandones commented on packages/framework/esm-styleguide/src/patient-banner/patient-banner-info/patient-banner-info.component.tsx
> +  // TODO: We ought to have some kind of "core translations."
Filed it https://openmrs.atlassian.net/browse/O3-2882

2024-03-10 17:07 UTC, raghavawasthi24 requested changes

2024-03-10 17:07 UTC, raghavawasthi24 commented on packages/framework/esm-styleguide/src/custom-overflow-menu/custom-overflow-menu.component.tsx
> +  deceased?: boolean;
decreased must not be optional because you are using it below

2024-03-10 17:07 UTC, raghavawasthi24 commented on packages/framework/esm-styleguide/src/custom-overflow-menu/custom-overflow-menu.component.tsx
> +          { [styles.deceased]: deceased },
If decreased is optional so whenever decreased is not passed as props , it will throw an error since it will be `undefined` in that case.

2024-03-11 12:17 UTC, ibacher commented on packages/framework/esm-framework/mock.tsx
> +  </div>
And what happens to the `{children}`?

2024-03-11 12:17 UTC, ibacher commented on packages/framework/esm-styleguide/src/custom-overflow-menu/custom-overflow-menu.component.tsx
> +          { [styles.deceased]: deceased },
Did you test your theory or look at what the `classnames()` library does?

2024-03-11 22:04 UTC, merged