O3-2823: Reuse signed in state in esm-core E2E tests excluding login …
openmrs/openmrs-esm-core pull request #921
Opened 2024-02-08 13:33 UTC by kdaud

…test

# Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [x] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [x] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary

## Screenshots

## Related Issue

https://issues.openmrs.org/browse/O3-2823

## Other

2024-02-08 16:06 UTC, Piumal1999 requested changes

2024-02-08 16:06 UTC, Piumal1999 commented on e2e/specs/logout.spec.ts
>    await test.step('When I click the `User` button', async () => {
Here you have to go to the homepage before clicking the user button. That's why the test is failing.

You can refer to [this](https://github.com/openmrs/openmrs-esm-patient-management/blob/main/e2e/pages/home-page.ts) and [this](https://github.com/openmrs/openmrs-esm-patient-management/blob/90ca8beba97580524d5ccfed10eb885e834589f1/e2e/specs/patient-search.spec.ts#L17-L21)

2024-02-09 10:09 UTC, Piumal1999 approved these changes
Looks good to me. Thanks @kdaud

2024-02-13 05:07 UTC, jayasanka-sack approved these changes
Thanks a bunch @kdaud ! 🧡

2024-02-13 05:08 UTC, merged