MF-497 : implementer-tool is not attaching to extention slot
openmrs/openmrs-esm-core pull request #93
Opened 2021-03-31 13:04 UTC by nk183

ticket https://issues.openmrs.org/browse/MF-497

esm-implementer-tools is registering an extension "implementer-tools-button" and attach it to "top-nav-actions-slot."
but the button is not visible I am not able to understand
@brandones @FlorianRappl can u please help

![image](https://user-images.githubusercontent.com/58779460/113148680-c16ab680-924f-11eb-97b1-1524326e1d91.png)

2021-03-31 15:28 UTC, brandones commented
The button is absolutely positioned right now.

You also need to make the button into a separate component, so that extension is only the button. The main popup component should remain as it is.

2021-04-01 11:26 UTC, nk183 commented
hi @brandones I have tried implementing this is what it looks like :
![image](https://user-images.githubusercontent.com/58779460/113286884-68ac2400-930a-11eb-9499-b851582e15d1.png)

can you please guide which CSS file should I work on I am a little confused as [ExtensionSlot](https://github.com/openmrs/openmrs-esm-primary-navigation/blob/797e828d4c63213919e8f7dcf8d4413df1b83ee2/src/components/navbar/navbar.component.tsx#L90) is showing boot the button

2021-04-01 12:12 UTC, FlorianRappl requested changes

2021-04-01 12:12 UTC, FlorianRappl commented on packages/esm-implementer-tools-app/src/index.ts
>      lifecycle: getAsyncLifecycle(
The whole lifecycle thing is no longer needed if you provide the button into the top nav.

Remove `lifecycle` and `activate`.

2021-04-01 13:48 UTC, nk183 commented on packages/esm-implementer-tools-app/src/index.ts
>      lifecycle: getAsyncLifecycle(
hi @FlorianRappl I have removed it Can you please check

2021-04-01 14:27 UTC, FlorianRappl commented on packages/esm-devtools-app/src/devtools/devtools.styles.css
> +  right: 8px;
Why do we need this trigger button? I thought it should go into the top nav bar?

I'd say let's remove this class.

2021-04-01 14:48 UTC, nk183 commented on packages/esm-devtools-app/src/devtools/devtools.styles.css
> +  right: 8px;
@FlorianRappl  I think you have mistaken this class is for `devtool button` .this change shifts the button to right.
The `implementer tool` is supposed to shift to `nav bar`.

2021-04-01 18:43 UTC, FlorianRappl commented on packages/esm-devtools-app/src/devtools/devtools.styles.css
> +  right: 8px;
Yeah you are right. This is in `devtools`!

2021-04-01 18:44 UTC, FlorianRappl approved these changes

2021-04-01 18:44 UTC, merged

2021-04-01 18:46 UTC, nk183 commented
hi @FlorianRappl  there was a bug in UI as I have mentioned above see this https://issues.openmrs.org/secure/attachment/60110/MF-497.mp4

2021-04-01 18:48 UTC, FlorianRappl commented
@nk183 and?

1. Fix it?
2. I don't think the bug was in this PR, or? I rather think it is in primary navigation / the slot usage.

2021-04-01 18:49 UTC, nk183 commented
yes you are right sorry
and I am woking on it