(bug) Ethiopia datepicker to resolve default, min and max values correctly
openmrs/openmrs-esm-core pull request #996
Opened 2024-05-15 15:36 UTC by kajambiya

# Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. Ensure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing#contributing-guidelines) label (such as `feat`, `fix`, or `chore`, among others). See existing PR titles for inspiration.

## For changes to apps

- [ ] My work conforms to the [**O3 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://om.rs/o3ui).

## If applicable

- [ ] My work includes tests or is validated by existing tests.
- [ ] I have updated the [esm-framework mock](https://github.com/openmrs/openmrs-esm-core/blob/main/packages/framework/esm-framework/mock.tsx) to reflect any API changes I have made.

## Summary
This pull request addresses an issue encountered with the locale datepicker functionality. When the locale was set to Amharic, the date picker incorrectly displayed the Ethiopian calendar with the wrong year. Specifically, when the maxValue prop was set to today's date, the calendar would display the year 2024 instead of the expected year 2016 in the Ethiopian calendar. This PR aims to rectify this issue.

## Screenshots

Uploading Screen Recording 2024-05-15 at 17.43.56.mov…

## Related Issue

## Other

2024-05-17 10:45 UTC, denniskigen submitted a review, later dismissed
LGTM

2024-05-17 12:23 UTC, ibacher requested changes

2024-05-17 12:23 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/react-spectrum/adobe-react-spectrum-date-wrapper.component.tsx
> +        maxValue={maxDate ? (parseToCalendarDate(maxDate, currentLocale) as CalendarDate) : undefined}
Instead of doing all this casting, the return type of `parseToCalendarDate()` should be declared as a `CalendarDate | undefined`. This is not only less code, but will ensure things are correct.

`parseToCalendarDate()` already handled `undefined` so the ternaries here are redundant.

2024-05-17 12:23 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/react-spectrum/adobe-react-spectrum-date-wrapper.component.tsx
> +  const parsedCalendarDate = parseDate(toLocalDateString(typeof date === 'string' ? parseDateString(date) : date));
This whole construction can be reduced to:

```suggestion
  const parsedCalendarDate = parseDate(dayjs(date).format('YYYY-MM-DD'));
```

2024-05-17 12:23 UTC, ibacher commented on packages/framework/esm-styleguide/src/datepicker/react-spectrum/locales.ts
> +};
There's no need to construct per-locale converters like this. You already have the calendars defined in the locale strings (or at least should) a la `am-AM-u-ca-ethiopic`, so you can create a generic utility:

```
function convertToLocaleCalendar(date: CalendarDate, locale: string | Intl.Locale) {
  let locale_ = typeof locale === 'string' ? new Intl.Locale(string) : locale;
  return toCalendar(date, createCalendar(locale_.calendar));
}
```

You can then change the locales for `am_ET` and `ti_ET` to `am-ET-u-ca-ethiopic` and `ti-ET-u-ca-ethiopic` (or whatever is appropriate).

Also it would be better to use the framework-provided `registerDefaultCalendar()` (if necessary) and `getDefaultCalendar()` rather than adding more locale utilities to the styleguide, which is not an appropriate place for hosting them.

2024-05-20 07:41 UTC, denniskigen commented
@kajambiya could you please remove the changes to the lockfile from your diff?

2024-05-20 09:44 UTC, denniskigen commented
I've merged the PR that possibly fixes the test failures. Please rebase.

2024-05-20 09:46 UTC, kajambiya commented
> I've merged the PR that possibly fixes the test failures. Please rebase.

Yah it actually does. Just updated the PR

2024-05-20 11:00 UTC, kajambiya commented on packages/framework/esm-styleguide/src/datepicker/react-spectrum/locales.ts
> +};
Thanks @ibacher 

Refactored the code accordingly.

2024-05-20 14:28 UTC, ibacher reviewed
Nice work! Just a little clean-up and should be g2g.

2024-05-20 14:28 UTC, ibacher commented on packages/framework/esm-utils/src/omrs-dates.ts
> +import { createCalendar, toCalendar, type CalendarDate } from '@internationalized/date';
`@internalized/date` needs to be added as a dependency of `esm-utils`.

2024-05-20 14:28 UTC, ibacher commented on packages/framework/esm-utils/src/omrs-dates.ts
> +  const localCalendarName = locale_.calendar;
If we're making the change here, I'd actually recommend this:

```ts
const localCalendarName = getDefaultCalendar(locale);
```

2024-05-20 15:54 UTC, kajambiya commented on packages/framework/esm-utils/src/omrs-dates.ts
> +import { createCalendar, toCalendar, type CalendarDate } from '@internationalized/date';
Done

2024-05-20 16:28 UTC, ibacher approved these changes

2024-05-20 16:28 UTC, merged